; GENERATED by accuracysnes-gen — do not edit by hand.
; Rendered scenes for the host framebuffer oracle (docs/adr/0013).
.p816
SCENES_IMPL = 1
.include "runtime.inc"

.segment "TESTS"

; c5-mode1-bg-priority — C5.02
; Mode 1 with BG1 and BG2 enabled at different priorities, each showing the font tiles already in VRAM through a distinct palette. Evidence for the mode-1 layer and priority ordering.
.proc scene_c5_mode1_bg_priority
    .a16
    .i16
    sep #$20
    .a8
    lda #$01
    sta $2105         ; BGMODE 1
    lda #$00
    sta $210B         ; BG1/BG2 character data at word $0000
    lda #(MAP_BASE >> 8)
    sta $2107         ; BG1 tilemap base
    lda #(MAP_BASE >> 8)
    sta $2108         ; BG2 tilemap base, same map so both layers show content
    lda #$03
    sta $212C         ; BG1 + BG2 on the main screen
    lda #$0F
    sta $2100         ; brightness 15, forced blank off
    rep #$30
    .a16
    .i16
    rts
.endproc

; c8-fixed-colour-add — C8.10
; Colour math in additive mode against the fixed colour, with the subscreen left as the fixed backdrop. Evidence for CGADSUB/COLDATA and the half/div2 behaviour.
.proc scene_c8_fixed_colour_add
    .a16
    .i16
    sep #$20
    .a8
    stz $2105         ; BGMODE 0
    lda #(MAP_BASE >> 8)
    sta $2107
    lda #$01
    sta $212C         ; BG1 on the main screen
    lda #$02
    sta $2130         ; CGWSEL: subscreen is the fixed colour
    lda #$21
    sta $2131         ; CGADSUB: add, applied to BG1
    lda #$9F
    sta $2132         ; COLDATA: blue = 31
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c10-mosaic-4x — C10.01
; Mosaic size 4 applied to BG1. Evidence that mosaic is applied after scrolling and anchored to the screen origin rather than the scroll origin.
.proc scene_c10_mosaic_4x
    .a16
    .i16
    sep #$20
    .a8
    stz $2105         ; BGMODE 0
    lda #(MAP_BASE >> 8)
    sta $2107
    lda #$01
    sta $212C
    lda #$31
    sta $2106         ; MOSAIC: size 4, enabled on BG1
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

.segment "CATALOG"
.export _scene_count
.export _scene_entries
_scene_count:
    .word 3
_scene_entries:
    .addr scene_c5_mode1_bg_priority
    .addr scene_c8_fixed_colour_add
    .addr scene_c10_mosaic_4x
