; GENERATED by accuracysnes-gen — do not edit by hand.
; Rendered scenes for the host framebuffer oracle (docs/adr/0013).
.p816
SCENES_IMPL = 1
.include "runtime.inc"

.segment "TESTS"

; Rewrite the tilemap with tile indices that both EXIST and are NON-BLANK in a deep mode.
;
; Two constraints, and missing the second is the subtler mistake. A tile must lie inside
; the font: 8bpp is 32 words/tile against a 1024-word font, so $00-$1F exist. It must also
; cover PRINTABLE glyphs, and how many glyphs a tile spans depends on the depth: a 4bpp
; tile covers glyphs 2T and 2T+1, an 8bpp tile covers 4T..4T+3. So $10-$1F is glyphs 32-63
; at 4bpp and 64-127 at 8bpp — printable at both. Anything below $10 lands on ASCII 0-31,
; the control characters, which are blank in this font.
;
; This cost two rounds. $00-$0F rendered an EMPTY screen in mode 2 while mode 4 looked
; fine, which reads as a broken mode; $08-$0F fixed 8bpp and left 4bpp still blank, which
; reads as a broken depth. Neither was true. An empty scene hashes stably and the
; reference emulators agree with it, so only looking at the picture finds this.
;
; WIDTH-NEUTRAL: P is saved and restored, so the A/X/Y widths on exit are
; exactly what they were on entry. Deliberate rather than merely tidy: the
; caller is generated assembly whose .a8/.a16 directives come from its OWN
; sep/rep lines, and a JSR is not one of those — so a helper that changed
; the width would leave the assembler believing one thing while the CPU did
; another, and the next immediate operand would be assembled at the wrong
; size. That failure already cost this project a debugging session; see the
; .a8/.a16 emission in `asm` below.
.proc scene_low_tiles
    php
    .a16
    .i16
    sep #$20
    .a8
    lda #$80
    sta VMAIN
    rep #$30
    .a16
    .i16
    ldx #MAP_BASE
    stx VMADDL
    ldx #$0000
@cell:
    txa
    lsr a
    lsr a
    lsr a
    lsr a
    lsr a             ; row
    sta f:V_TMP2
    txa
    clc
    adc f:V_TMP2      ; tile varies with row AND column: a column-constant map cannot
                      ; show a vertical shift, which is how the first OPT scenes came
                      ; out identical to their own control.
    and #$000F
    ora #$0010        ; tile $10-$1F: inside the font AND printable at 4bpp and 8bpp
    sta f:V_TMP
    lda f:V_TMP2
    and #$0007
    .repeat 10
    asl a
    .endrepeat
    ora f:V_TMP       ; palette in bits 10-12
    sta VMDATAL
    inx
    cpx #(SCREEN_COLS * 32)
    bne @cell
    plp               ; restore the caller's register widths
    rts
.endproc

; Fill BG3's tilemap with offset-per-tile entries (see scenes.rs::opt_map_helper).
; Reads V_OPT_H_EVEN / V_OPT_H_ODD (row 0) and V_OPT_V_EVEN / V_OPT_V_ODD (row 1).
.proc scene_opt_map
    php
    .a16
    .i16
    sep #$20
    .a8
    lda #$80
    sta VMAIN
    rep #$30
    .a16
    .i16
    ldx #OPT_MAP_BASE
    stx VMADDL
    ldx #$0000                ; cell index across the whole 32x32 map
@cell:
    txa
    cmp #SCREEN_COLS          ; row 0?
    bcs :+
    bcc @row0
  :
    cmp #(SCREEN_COLS * 2)    ; row 1?
    bcc @row1
    lda #$0000                ; every other row is empty
    bra @put
@row0:
    txa
    and #$0001
    bne :+
    lda f:V_OPT_H_EVEN
    bra @put
  :
    lda f:V_OPT_H_ODD
    bra @put
@row1:
    txa
    and #$0001
    bne :+
    lda f:V_OPT_V_EVEN
    bra @put
  :
    lda f:V_OPT_V_ODD
@put:
    sta VMDATAL
    inx
    cpx #(SCREEN_COLS * 32)
    bne @cell
    plp                       ; restore the caller's register widths
    rts
.endproc

; Mode 7 VRAM: tilemap in the low bytes, character data in the high bytes, one pass.
.proc scene_mode7_vram
    php
    .a16
    .i16
    sep #$20
    .a8
    lda #$80
    sta VMAIN
    rep #$30
    .a16
    .i16
    ldx #$0000
    stx VMADDL
@cell:
    ; low byte = tilemap entry: a 16x16 grid of distinct tiles across the 128x128 map.
    txa
    and #$007F                ; map column 0-127
    lsr a
    lsr a
    lsr a                     ; column / 8 -> 0-15
    sta f:V_TMP
    txa
    lsr a
    lsr a
    lsr a
    lsr a
    lsr a
    lsr a
    lsr a                     ; map row 0-127
    lsr a
    lsr a
    lsr a                     ; row / 8 -> 0-15
    asl a
    asl a
    asl a
    asl a                     ; row block * 16
    ora f:V_TMP               ; tile 0-255, distinct per 8x8 block of the map
    and #$00FF
    sta f:V_TMP
    ; high byte = character data: the word index PLUS ONE, so each tile is a colour
    ; gradient and character 0's pixel (0,0) is non-zero. That last part matters: at a
    ; large zoom every out-of-range pixel samples the same sub-pixel, so if char 0 pixel
    ; (0,0) were colour 0 the char-0 screen-over mode would render transparent and be
    ; indistinguishable from the transparent mode -- which it was, on all three emulators.
    txa
    inc a
    and #$00FF
    xba                       ; into the high byte
    ora f:V_TMP
    sta VMDATAL               ; one 16-bit store writes both halves
    inx
    cpx #$4000                ; 16384 words = the whole Mode 7 area
    bne @cell
    plp
    rts
.endproc
; Fill the tilemap screen after the canvas (see scenes.rs::second_screen_helper).
.proc scene_second_screen
    php
    .a16
    .i16
    sep #$20
    .a8
    lda #$80
    sta VMAIN
    rep #$30
    .a16
    .i16
    ldx #(MAP_BASE + $400)   ; the second 32x32 screen, one screen on from the canvas
    stx VMADDL
    ldx #$0000
@cell:
    txa
    and #$000F
    ora #$0020        ; tiles $20-$2F: printable, and outside the canvas's $10-$1F
    ora #$1400        ; palette 5, which the canvas's row-derived palettes do not favour
    sta VMDATAL
    inx
    cpx #(SCREEN_COLS * 32)
    bne @cell
    plp
    rts
.endproc

; Park all 128 sprites off-screen and point OBJ character data at the font.
.proc scene_oam_reset
    php
    .a16
    .i16
    sep #$20
    .a8
    lda #$20
    sta $2101         ; OBJSEL: size pair 1 (8x8 / 16x16), name base word $0000
    rep #$10
    .i16
    ldx #$0000
    stx $2102         ; OAMADD = 0

    ; A stays 8-bit and X stays 16-bit for both loops. OAM is written a byte at a time and
    ; the counters only need the index width, so flipping the accumulator inside the loop
    ; would be 160 pointless `sep`/`rep` pairs and one more place to get a width wrong.
    ldx #$0000
@low:
    lda #$00
    sta $2104         ; X low
    lda #224
    sta $2104         ; Y = 224: off the bottom, so no range or sliver slot is used
    lda #$00
    sta $2104         ; tile
    sta $2104         ; attributes
    inx
    cpx #128
    bne @low
    ldx #$0000
    lda #$00
@high:
    sta $2104         ; high table: X bit 8 clear, size bit clear
    inx
    cpx #32
    bne @high
    plp
    rts
.endproc

; c5-mode1-bg-priority — C5.02
; Mode 1 with BG1 and BG2 enabled at different priorities, each showing the font tiles already in VRAM through a distinct palette. Evidence for the mode-1 layer and priority ordering.
.proc scene_c5_mode1_bg_priority
    .a16
    .i16
    sep #$20
    .a8
    lda #$01
    sta $2105         ; BGMODE 1
    lda #$00
    sta $210B         ; BG1/BG2 character data at word $0000
    lda #(MAP_BASE >> 8)
    sta $2107         ; BG1 tilemap base
    lda #(MAP_BASE >> 8)
    sta $2108         ; BG2 tilemap base, same map so both layers show content
    lda #$03
    sta $212C         ; BG1 + BG2 on the main screen
    lda #$0F
    sta $2100         ; brightness 15, forced blank off
    rep #$30
    .a16
    .i16
    rts
.endproc

; c8-fixed-colour-add — C8.11
; Colour math in additive mode against the fixed colour, with the subscreen left as the fixed backdrop. Evidence for CGADSUB/COLDATA and the half/div2 behaviour.
.proc scene_c8_fixed_colour_add
    .a16
    .i16
    sep #$20
    .a8
    stz $2105         ; BGMODE 0
    lda #(MAP_BASE >> 8)
    sta $2107
    lda #$01
    sta $212C         ; BG1 on the main screen
    lda #$02
    sta $2130         ; CGWSEL: subscreen is the fixed colour
    lda #$21
    sta $2131         ; CGADSUB: add, applied to BG1
    lda #$9F
    sta $2132         ; COLDATA: blue = 31
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c10-mosaic-4x — C10.01
; Mosaic size 4 applied to BG1. Evidence that mosaic is applied after scrolling and anchored to the screen origin rather than the scroll origin.
.proc scene_c10_mosaic_4x
    .a16
    .i16
    sep #$20
    .a8
    stz $2105         ; BGMODE 0
    lda #(MAP_BASE >> 8)
    sta $2107
    lda #$01
    sta $212C
    lda #$31
    sta $2106         ; MOSAIC: size 4, enabled on BG1
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c5-mode0-four-bg-priority — C5.01
; Mode 0 with all four backgrounds enabled, each scrolled by a different amount so the lower layers show through the transparent pixels of the ones above. Evidence for the mode-0 priority order and for four independent 2bpp layers existing at all.
.proc scene_c5_mode0_four_bg_priority
    .a16
    .i16
    sep #$20
    .a8
    stz $2105         ; BGMODE 0: four 2bpp layers
    stz $210B
    stz $210C         ; all four BGs take character data from word $0000
    lda #(MAP_BASE >> 8)
    sta $2107
    sta $2108
    sta $2109
    sta $210A         ; one tilemap, four layers — the difference is scroll and palette
    ; Scroll each layer by a different amount. Without this the higher-priority layer
    ; covers the others exactly and the priority order is unobservable.
    lda #$04
    sta $210F
    stz $210F         ; BG2 H scroll = 4
    lda #$08
    sta $2111
    stz $2111         ; BG3 H scroll = 8
    lda #$0C
    sta $2113
    stz $2113         ; BG4 H scroll = 12
    lda #$0F
    sta $212C         ; BG1-4 all on the main screen
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c5-mode0-palette-segregation — C5.09
; Mode 0 again, but read for colour rather than order: each background takes its palette from its own 32-entry CGRAM region (BG1 0-31, BG2 32-63, BG3 64-95, BG4 96-127). The canvas fills all 128 entries with distinct colours, so a core that ignores the per-BG offset renders the four layers in the same colours.
.proc scene_c5_mode0_palette_segregation
    .a16
    .i16
    sep #$20
    .a8
    stz $2105
    stz $210B
    stz $210C
    lda #(MAP_BASE >> 8)
    sta $2107
    sta $2108
    sta $2109
    sta $210A
    ; Vertical rather than horizontal offsets this time, so the layers interleave by row
    ; and each region's colours land in a different part of the picture.
    lda #$02
    sta $2110
    stz $2110         ; BG2 V scroll = 2
    lda #$04
    sta $2112
    stz $2112         ; BG3 V scroll = 4
    lda #$06
    sta $2114
    stz $2114         ; BG4 V scroll = 6
    lda #$0F
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c5-mode3-8bpp — C5.04
; Mode 3: BG1 8bpp, BG2 4bpp, both reading the same VRAM. The extra bitplanes are zero (the canvas only writes a 2bpp font), so this pins how a core assembles a deeper pixel from planes that are not all present — deterministic, because the VRAM it reads was cleared before the font was loaded.
.proc scene_c5_mode3_8bpp
    .a16
    .i16
    sep #$20
    .a8
    lda #$03
    sta $2105         ; BGMODE 3
    stz $210B
    lda #(MAP_BASE >> 8)
    sta $2107
    sta $2108
    jsr scene_low_tiles ; 8bpp tiles are 32 words; the canvas map indexes past the font
    lda #$03
    sta $212C         ; BG1 + BG2
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c5-tilemap-flip-bits — C5.10
; The tilemap entry's H and V flip bits (bits 14 and 15 of `vhopppcc cccccccc`). The canvas writes neither, so this scene rewrites the tilemap with both set on alternating cells — a core that ignores a flip bit, or swaps the two, renders recognisably different glyphs rather than subtly wrong ones.
.proc scene_c5_tilemap_flip_bits
    .a16
    .i16
    sep #$20
    .a8
    stz $2105
    lda #(MAP_BASE >> 8)
    sta $2107
    stz $210B
    ; Rewrite the tilemap: cell index bit 0 picks H flip, bit 5 (row parity) picks V flip.
    lda #$80
    sta $2115         ; VMAIN: increment after the high byte, so a 16-bit store = one entry
    rep #$30
    .a16
    .i16
    ldx #MAP_BASE
    stx $2116
    ldx #$0000
    @flipcell:
    txa
    and #$003F
    clc
    adc #$0041        ; a letter glyph, so a flip is obvious
    sta f:V_TMP
    txa
    and #$0001
    beq :+
    lda #$4000        ; H flip
    bra :++
    :
    lda #$0000
    :
    sta f:V_TMP2
    txa
    and #$0020        ; every other row of cells
    beq :+
    lda #$8000        ; V flip
    bra :++
    :
    lda #$0000
    :
    ora f:V_TMP2
    ora f:V_TMP
    sta $2118
    inx
    cpx #(SCREEN_COLS * 32)
    bne @flipcell
    sep #$20
    .a8
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c5-16x16-tiles — C5.11
; BG1 switched to 16x16 tiles (BGMODE bit 4). A 16x16 cell is assembled from the named tile plus +1, +16 and +17, so a core that uses the wrong neighbour renders the right glyphs in the wrong quadrants — visible, and specific about which quadrant is wrong.
.proc scene_c5_16x16_tiles
    .a16
    .i16
    sep #$20
    .a8
    lda #$10
    sta $2105         ; BGMODE 0 with BG1 in 16x16 tiles
    stz $210B
    lda #(MAP_BASE >> 8)
    sta $2107
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c8-subtract-mode — C8.10
; Colour math in SUBTRACT mode (`$2131` bit 7) against the fixed colour, the counterpart to `c8-fixed-colour-add`. Together they pin the sign: a core that ignores bit 7 renders the two scenes identically.
.proc scene_c8_subtract_mode
    .a16
    .i16
    sep #$20
    .a8
    stz $2105
    lda #(MAP_BASE >> 8)
    sta $2107
    stz $210B
    lda #$01
    sta $212C
    lda #$02
    sta $2130         ; CGWSEL: the subscreen is the fixed colour
    lda #$A1
    sta $2131         ; CGADSUB: subtract, applied to BG1 and the backdrop
    lda #$9F
    sta $2132         ; COLDATA: blue = 31
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c8-clamp-no-wrap — C8.02
; Additive colour math driven hard enough to saturate every channel. Results clamp at 31 and do not wrap, so the bright areas go white and stay white — a core that wraps produces dark speckle exactly where the picture should be brightest, which is unmistakable rather than subtle.
.proc scene_c8_clamp_no_wrap
    .a16
    .i16
    sep #$20
    .a8
    stz $2105
    lda #(MAP_BASE >> 8)
    sta $2107
    stz $210B
    lda #$01
    sta $212C
    lda #$02
    sta $2130
    lda #$21
    sta $2131         ; add
    lda #$FF
    sta $2132         ; COLDATA: all three channel selects, value 31 — saturate everything
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c8-half-ignored-on-fixed-backdrop — C8.03
; Identical to `c8-fixed-colour-add` except that CGADSUB's half/div2 bit is set. The documented behaviour is that half is IGNORED when the subscreen is the fixed backdrop, so this scene must hash the same as that one. Two scenes that must agree is a stronger statement than one scene that must match a number.
.proc scene_c8_half_ignored_on_fixed_backdrop
    .a16
    .i16
    sep #$20
    .a8
    stz $2105
    lda #(MAP_BASE >> 8)
    sta $2107
    stz $210B
    lda #$01
    sta $212C
    lda #$02
    sta $2130         ; CGWSEL: the subscreen is the fixed colour
    lda #$61
    sta $2131         ; CGADSUB: add + HALF, applied to BG1
    lda #$9F
    sta $2132         ; COLDATA: blue = 31, as in the add scene
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c8-window-bounds-inclusive — C8.04
; Window 1 set to 64..191 and used to clip BG1 on the main screen. Both bounds are inclusive, so the masked band is 128 pixels wide — a core with an exclusive edge is off by one column at a hard black/colour boundary, which a hash catches even though an eye would not.
.proc scene_c8_window_bounds_inclusive
    .a16
    .i16
    sep #$20
    .a8
    stz $2105
    lda #(MAP_BASE >> 8)
    sta $2107
    stz $210B
    lda #$01
    sta $212C
    lda #$02
    sta $2123         ; W12SEL: BG1 uses window 1, not inverted
    lda #64
    sta $2126         ; WH0: window 1 left edge
    lda #191
    sta $2127         ; WH1: window 1 right edge
    lda #$01
    sta $212E         ; TMW: clip BG1 on the main screen
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c8-window-left-gt-right-empty — C8.05
; The same window with its bounds crossed (left 200, right 50). That is an EMPTY window, not a wrapped one: BG1 stays fully visible. A core that treats the pair as a wraparound range clips both ends of the screen instead.
.proc scene_c8_window_left_gt_right_empty
    .a16
    .i16
    sep #$20
    .a8
    stz $2105
    lda #(MAP_BASE >> 8)
    sta $2107
    stz $210B
    lda #$01
    sta $212C
    lda #$02
    sta $2123
    lda #200
    sta $2126
    lda #50
    sta $2127         ; left > right
    lda #$01
    sta $212E
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c8-window-inverted-empty-is-full — C8.06
; The crossed bounds again, with window 1 inverted. An inverted empty window is a FULL one, so BG1 disappears entirely and the backdrop is all that remains. Paired with the previous scene this pins the inversion as acting on the region rather than on the comparison.
.proc scene_c8_window_inverted_empty_is_full
    .a16
    .i16
    sep #$20
    .a8
    stz $2105
    lda #(MAP_BASE >> 8)
    sta $2107
    stz $210B
    lda #$01
    sta $212C
    lda #$03
    sta $2123         ; W12SEL: BG1 uses window 1, INVERTED
    lda #200
    sta $2126
    lda #50
    sta $2127
    lda #$01
    sta $212E
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c8-both-windows-disabled-empty — C8.07
; TMW clips BG1, but neither window is enabled for it in W12SEL. The combined mask is EMPTY, not full — BG1 stays fully visible. This is the errata case: the intuitive reading is that clipping with no window means clipping everything, and a core that implements the intuition blanks the layer.
.proc scene_c8_both_windows_disabled_empty
    .a16
    .i16
    sep #$20
    .a8
    stz $2105
    lda #(MAP_BASE >> 8)
    sta $2107
    stz $210B
    lda #$01
    sta $212C
    stz $2123         ; W12SEL: neither window enabled for BG1
    lda #64
    sta $2126
    lda #191
    sta $2127         ; bounds set, but no window selects them
    lda #$01
    sta $212E         ; TMW: clip BG1 anyway
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c8-window-logic-xor — C8.08
; Both windows enabled for BG1 and combined with XOR: window 1 covers 32..159, window 2 covers 96..223, so the mask is the two non-overlapping wings and the 64-pixel overlap is left alone. Each of OR, AND, XOR and XNOR produces a visibly different band pattern, so picking the wrong one cannot pass.
.proc scene_c8_window_logic_xor
    .a16
    .i16
    sep #$20
    .a8
    stz $2105
    lda #(MAP_BASE >> 8)
    sta $2107
    stz $210B
    lda #$01
    sta $212C
    lda #$0A
    sta $2123         ; W12SEL: BG1 uses window 1 AND window 2, neither inverted
    lda #32
    sta $2126
    lda #159
    sta $2127         ; window 1
    lda #96
    sta $2128
    lda #223
    sta $2129         ; window 2, overlapping
    lda #$02
    sta $212A         ; WBGLOG: BG1 combines its two windows with XOR
    lda #$01
    sta $212E
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c10-mosaic-screen-anchored — C10.02
; Mosaic 4 with BG1 scrolled by 2 pixels in each axis — deliberately not a multiple of the mosaic size. The block grid stays anchored to the top-left of the SCREEN, so the content moves through a stationary grid. A core that anchors to the scroll origin instead produces the same picture shifted, which the `c10-mosaic-4x` scene alone cannot distinguish.
.proc scene_c10_mosaic_screen_anchored
    .a16
    .i16
    sep #$20
    .a8
    stz $2105
    lda #(MAP_BASE >> 8)
    sta $2107
    stz $210B
    lda #$02
    sta $210D
    stz $210D         ; BG1 H scroll = 2
    lda #$02
    sta $210E
    stz $210E         ; BG1 V scroll = 2
    lda #$01
    sta $212C
    lda #$31
    sta $2106         ; MOSAIC: size 4, enabled on BG1
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c12-direct-colour-mode3 — C12.01,C12.03
; Direct colour mode (CGWSEL bit 0) on Mode 3's 8bpp BG1, where the pixel value supplies the colour directly instead of indexing CGRAM. Only modes 3, 4 and 7 offer it, so this also pins that CGRAM is bypassed rather than merely reordered: the canvas's 128 palette entries stop mattering entirely.
.proc scene_c12_direct_colour_mode3
    .a16
    .i16
    sep #$20
    .a8
    lda #$03
    sta $2105         ; BGMODE 3 — 8bpp BG1, a precondition for direct colour
    stz $210B
    lda #(MAP_BASE >> 8)
    sta $2107
    jsr scene_low_tiles ; without this every 8bpp pixel reads zero and the screen is empty
    lda #$01
    sta $212C
    lda #$01
    sta $2130         ; CGWSEL bit 0: direct colour
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c5-mode2-plain — C5.03
; Mode 2 with BG1 and BG2 displayed and offset-per-tile left inert (BG3's table is all zeroes, so no entry carries an enable bit). The control for the `c6-*` scenes: if this renders and they do not, the fault is in their setup rather than in the mode. It is also `C5.03`'s own evidence, which is why it is a scene and not a scratch file.
.proc scene_c5_mode2_plain
    .a16
    .i16
    sep #$20
    .a8
    lda #$02
    sta $2105         ; BGMODE 2
    stz $210B
    lda #(MAP_BASE >> 8)
    sta $2107
    sta $2108
    lda #(OPT_MAP_BASE >> 8)
    sta $2109
    jsr scene_low_tiles ; 4bpp tiles are 16 words; the canvas map indexes past the font
    rep #$30
    .a16
    .i16
    lda #$0000
    sta f:V_OPT_H_EVEN
    sta f:V_OPT_H_ODD
    sta f:V_OPT_V_EVEN
    sta f:V_OPT_V_ODD ; an all-zero table: no entry has an enable bit set
    jsr scene_opt_map
    sep #$20
    .a8
    lda #$03
    sta $212C         ; BG1 + BG2
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c6-opt-v-alternating-columns — C6.05,C6.06
; Mode 2 offset-per-tile: BG3's row-1 entries give even columns a vertical offset of 100 and odd columns none. 100 rather than a rounder number because an offset that is a multiple of 16 is invisible against a 16-tile cycle, and one that is a multiple of 8 leaves the glyph row unchanged — the first version of this scene arranged a shift nothing could show. Two assertions at once — each entry moves a WHOLE tile column (C6.06), and the leftmost tile is never affected, so the first entry controls the SECOND visible column (C6.05, an errata). Alternating rather than uniform offsets is what makes the second one legible: the shifted columns come out odd-numbered, and a core without the exemption shifts the even ones instead.
.proc scene_c6_opt_v_alternating_columns
    .a16
    .i16
    sep #$20
    .a8
    lda #$02
    sta $2105         ; BGMODE 2 — BG1/BG2 4bpp, BG3 is the offset table
    stz $210B         ; BG1/BG2 character data at word $0000
    lda #(MAP_BASE >> 8)
    sta $2107         ; BG1 tilemap
    lda #(OPT_MAP_BASE >> 8)
    sta $2109         ; BG3 tilemap = the offset table
    jsr scene_low_tiles ; 4bpp tiles are 16 words; the canvas map indexes past the font
    rep #$30
    .a16
    .i16
    lda #$0000
    sta f:V_OPT_H_EVEN
    sta f:V_OPT_H_ODD ; no horizontal offsets in this scene
    lda #($2000 | 100) ; bit 13 = applies to BG1; 100 rows down — deliberately NOT a
                       ; multiple of 8, so the glyph row shifts too and the offset is
                       ; visible whatever the tilemap happens to contain
    sta f:V_OPT_V_EVEN
    lda #$0000
    sta f:V_OPT_V_ODD
    jsr scene_opt_map
    sep #$20
    .a8
    lda #$01
    sta $212C         ; BG1 only — BG3 is a table here, not a layer
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c6-opt-v-replaces-vofs — C6.04
; The same vertical offset of 100, but with BG1VOFS already set to 32. An offset-per-tile V entry REPLACES the background's own scroll rather than adding to it, so the offset columns land at row 100 and not at 132. The unaffected columns still show the scroll, which is what makes the two behaviours distinguishable in one picture.
.proc scene_c6_opt_v_replaces_vofs
    .a16
    .i16
    sep #$20
    .a8
    lda #$02
    sta $2105
    stz $210B
    lda #(MAP_BASE >> 8)
    sta $2107
    lda #(OPT_MAP_BASE >> 8)
    sta $2109
    jsr scene_low_tiles
    sep #$20
    .a8
    lda #32
    sta $210E
    stz $210E         ; BG1VOFS = 32
    rep #$30
    .a16
    .i16
    lda #$0000
    sta f:V_OPT_H_EVEN
    sta f:V_OPT_H_ODD
    lda #($2000 | 100) ; not a multiple of 8 — see c6-opt-v-alternating-columns
    sta f:V_OPT_V_EVEN
    lda #$0000
    sta f:V_OPT_V_ODD
    jsr scene_opt_map
    sep #$20
    .a8
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c6-opt-h-keeps-fine-scroll — C6.03
; A horizontal offset-per-tile entry of 64 with BG1HOFS = 5. Unlike the vertical case, an H entry replaces only the COARSE part of the scroll — the background's own low three HOFS bits survive, so the offset columns sit at 64+5 rather than at 64. Five pixels is small, and a hash notices it where an eye would not. (64 is fine for an H entry precisely because the low three bits are discarded anyway; only the V case needs an offset that is not a multiple of 8.)
.proc scene_c6_opt_h_keeps_fine_scroll
    .a16
    .i16
    sep #$20
    .a8
    lda #$02
    sta $2105
    stz $210B
    lda #(MAP_BASE >> 8)
    sta $2107
    lda #(OPT_MAP_BASE >> 8)
    sta $2109
    jsr scene_low_tiles
    sep #$20
    .a8
    lda #5
    sta $210D
    stz $210D         ; BG1HOFS = 5 — the fine bits that must survive
    rep #$30
    .a16
    .i16
    lda #($2000 | 64)
    sta f:V_OPT_H_EVEN
    lda #$0000
    sta f:V_OPT_H_ODD
    sta f:V_OPT_V_EVEN
    sta f:V_OPT_V_ODD
    jsr scene_opt_map
    sep #$20
    .a8
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c6-opt-enable-bit-bg1 — C6.01
; Both BG1 and BG2 are displayed and the offset entries carry bit 13 only. Only BG1 moves. Paired with `c6-opt-enable-bit-bg2` this pins which bit belongs to which layer — neither scene alone can, because a core that swaps the two bits produces a picture that is equally plausible until the pair is compared.
.proc scene_c6_opt_enable_bit_bg1
    .a16
    .i16
    sep #$20
    .a8
    lda #$02
    sta $2105
    stz $210B
    lda #(MAP_BASE >> 8)
    sta $2107
    sta $2108         ; BG2 shows the same map, so a shift is visible on either layer
    lda #(OPT_MAP_BASE >> 8)
    sta $2109
    jsr scene_low_tiles
    sep #$20
    .a8
    lda #8
    sta $2110
    stz $2110         ; BG2 scrolled down 8 so the two layers are separable
    rep #$30
    .a16
    .i16
    lda #$0000
    sta f:V_OPT_H_EVEN
    sta f:V_OPT_H_ODD
    lda #($2000 | 100) ; bit 13: BG1 only
    sta f:V_OPT_V_EVEN
    lda #$0000
    sta f:V_OPT_V_ODD
    jsr scene_opt_map
    sep #$20
    .a8
    lda #$03
    sta $212C         ; BG1 + BG2
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c6-opt-enable-bit-bg2 — C6.01
; Identical to `c6-opt-enable-bit-bg1` except that the entries carry bit 14 instead of bit 13, so BG2 moves and BG1 does not. The two scenes must NOT hash the same; a core that treats the two bits alike renders them identically.
.proc scene_c6_opt_enable_bit_bg2
    .a16
    .i16
    sep #$20
    .a8
    lda #$02
    sta $2105
    stz $210B
    lda #(MAP_BASE >> 8)
    sta $2107
    sta $2108
    lda #(OPT_MAP_BASE >> 8)
    sta $2109
    jsr scene_low_tiles
    sep #$20
    .a8
    lda #8
    sta $2110
    stz $2110
    rep #$30
    .a16
    .i16
    lda #$0000
    sta f:V_OPT_H_EVEN
    sta f:V_OPT_H_ODD
    lda #($4000 | 100) ; bit 14: BG2 only
    sta f:V_OPT_V_EVEN
    lda #$0000
    sta f:V_OPT_V_ODD
    jsr scene_opt_map
    sep #$20
    .a8
    lda #$03
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c6-mode4-h-vs-v-select — C6.02
; Mode 4 packs both offsets into a single row and picks between them with bit 15: clear selects horizontal, set selects vertical. Even columns get a horizontal offset of 64, odd columns a vertical one of 100 — deliberately different, because an H entry discards its low three bits while a V entry does not, so the two need different values to be equally visible. A core that reads the selector backwards displaces the columns along the wrong axis, which is unmistakable.
.proc scene_c6_mode4_h_vs_v_select
    .a16
    .i16
    sep #$20
    .a8
    lda #$04
    sta $2105         ; BGMODE 4 — BG1 8bpp, BG2 2bpp, BG3 is the offset table
    stz $210B
    lda #(MAP_BASE >> 8)
    sta $2107
    lda #(OPT_MAP_BASE >> 8)
    sta $2109
    jsr scene_low_tiles ; 8bpp tiles are 32 words — mandatory here
    rep #$30
    .a16
    .i16
    lda #($2000 | 64) ; bit 15 clear: horizontal, applied to BG1
    sta f:V_OPT_H_EVEN
    lda #($A000 | 100) ; bit 15 set: vertical (not a multiple of 8)
    sta f:V_OPT_H_ODD
    lda #$0000
    sta f:V_OPT_V_EVEN
    sta f:V_OPT_V_ODD ; mode 4 reads row 0 only
    jsr scene_opt_map
    sep #$20
    .a8
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c11-mode7-identity — C5.08,C11.05
; Mode 7 with the identity matrix and no scroll: one screen pixel is one map pixel. The baseline the other Mode 7 scenes are read against, and evidence for the byte-interleaved VRAM layout on its own — a core that reads the tilemap from the high bytes and the characters from the low bytes renders noise rather than the 16x16 grid of gradient tiles this lays down.
.proc scene_c11_mode7_identity
    .a16
    .i16
    sep #$20
    .a8
    lda #$07
    sta $2105         ; BGMODE 7
    jsr scene_mode7_vram
    sep #$20
    .a8
    stz $211A         ; M7SEL: no flip, screen-over = wrap
    stz $211B
    lda #$01
    sta $211B         ; M7A = $0100 (1.0)
    stz $211C
    stz $211C         ; M7B = 0
    stz $211D
    stz $211D         ; M7C = 0
    stz $211E
    sta $211E         ; M7D = $0100 (1.0)
    stz $211F
    stz $211F         ; M7X = 0
    stz $2120
    stz $2120         ; M7Y = 0
    lda #$01
    sta $212C         ; BG1 — the only layer Mode 7 has without EXTBG
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c5-mode4-two-layers — C5.05
; Mode 4 with BG1 and BG2 both displayed. The mode's shape is unlike its neighbours: BG1 is 8bpp and BG2 is 2bpp — three bits of colour depth apart, from the same tilemap — and BG3 exists only as the offset-per-tile table, which is left inert here so this scene is about the mode's layers rather than about OPT. A core that reuses mode 3's depths, or mode 2's layer set, renders both layers at the wrong depth and the difference is not subtle.
.proc scene_c5_mode4_two_layers
    .a16
    .i16
    sep #$20
    .a8
    lda #$04
    sta $2105         ; BGMODE 4
    stz $210B
    lda #(MAP_BASE >> 8)
    sta $2107
    sta $2108         ; BG1 and BG2 share the canvas map
    lda #(OPT_MAP_BASE >> 8)
    sta $2109         ; BG3 is mode 4's offset table
    jsr scene_low_tiles
    rep #$30
    .a16
    .i16
    lda #$0000
    sta f:V_OPT_H_EVEN
    sta f:V_OPT_H_ODD
    sta f:V_OPT_V_EVEN
    sta f:V_OPT_V_ODD
    jsr scene_opt_map     ; all zeroes: no entry carries an enable bit
    sep #$20
    .a8
    lda #$03
    sta $212C         ; BG1 and BG2 on the main screen
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c5-bgsc-64x32-second-map-right — C5.12
; BG1 sized 64x32 and scrolled 256 pixels, so the display sits entirely in the second tilemap screen. A 64-wide map places that screen to the RIGHT of the first, and `scene_second_screen` fills it with a marker the canvas never uses — so the correct picture is the marker, and a core that ignores the size bits, or places the extra screen below as a 32x64 map would, wraps back into the canvas instead. The marker exists because the canvas repeats every 256 pixels: without it, scrolling into the second screen renders a picture identical to not scrolling at all.
.proc scene_c5_bgsc_64x32_second_map_right
    .a16
    .i16
    sep #$20
    .a8
    stz $2105         ; BGMODE 0
    lda #((MAP_BASE >> 8) | $01)
    sta $2107         ; BG1SC: canvas base, size bits 01 = 64x32
    jsr scene_second_screen
    sep #$20
    .a8
    stz $210D
    lda #$01
    sta $210D         ; BG1HOFS = $0100 — one whole screen to the right
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c5-mode7-ignores-bgsc — C5.13
; The identity Mode 7 scene again, with BG1SC and BG1NBA deliberately pointed at nonsense first. Mode 7 has its own fixed VRAM layout — byte-interleaved tilemap and characters at $0000 — and reads neither register, so the picture must be exactly the one `c11-mode7-identity` produces. That equality is the assertion, declared as an equivalence in the harness rather than as a second committed hash: a core that honours BG1SC in Mode 7 renders from the wrong address and fails it, while a change to the shared Mode 7 canvas moves both scenes together and leaves it holding.
.proc scene_c5_mode7_ignores_bgsc
    .a16
    .i16
    sep #$20
    .a8
    lda #$07
    sta $2105         ; BGMODE 7
    ; Nonsense in both registers BEFORE the VRAM upload, so nothing can be read from them.
    lda #$7B
    sta $2107         ; BG1SC: base word $7800, 64x64 — a long way from Mode 7's $0000
    lda #$0F
    sta $210B         ; BG1NBA: character base $F000 words
    jsr scene_mode7_vram
    sep #$20
    .a8
    stz $211A         ; M7SEL: no flip, screen-over = wrap
    stz $211B
    lda #$01
    sta $211B         ; M7A = $0100 (1.0)
    stz $211C
    stz $211C         ; M7B = 0
    stz $211D
    stz $211D         ; M7C = 0
    stz $211E
    sta $211E         ; M7D = $0100 (1.0)
    stz $211F
    stz $211F         ; M7X = 0
    stz $2120
    stz $2120         ; M7Y = 0
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c11-org-13bit-mask — C11.02
; Mode 7 with screen-over set to TRANSPARENT and `M7HOFS = $0C40`, which is the only arrangement in which the origin's 13-bit mask is visible at all. `ORG.X` is `(M7HOFS - M7X) AND NOT $1C00`, so the mask clears bits 10-12 and $0C40 becomes 64 — inside the map, and the picture is an ordinary offset view. Without the mask the origin is 3136, far outside a 1024x1024 map, and every pixel is transparent. $0C40 rather than $1C40 because M7HOFS is thirteen bits SIGNED: with bit 12 set the value is negative, the origin is off the map to the left either way, and the mask turns into a no-op that changes nothing — which is what a first attempt at this scene rendered. The wrap setting hides this completely: $1C00 is 7 * $400, so the mask only ever removes multiples of 1024, which is exactly what wrapping removes anyway. A first version of this scene left screen-over at wrap and rendered a picture identical to `c11-mode7-identity` on all three emulators — a stable hash that showed nothing.
.proc scene_c11_org_13bit_mask
    .a16
    .i16
    sep #$20
    .a8
    lda #$07
    sta $2105         ; BGMODE 7
    jsr scene_mode7_vram
    sep #$20
    .a8
    lda #$80
    sta $211A         ; M7SEL: screen-over = transparent outside the map
    stz $211B
    lda #$01
    sta $211B         ; M7A = $0100 (1.0)
    stz $211C
    stz $211C         ; M7B = 0
    stz $211D
    stz $211D         ; M7C = 0
    stz $211E
    sta $211E         ; M7D = $0100 (1.0)
    stz $211F
    stz $211F         ; M7X = 0
    stz $2120
    stz $2120         ; M7Y = 0
    ; M7HOFS = $0C40, positive in thirteen bits. Masked it is 64; unmasked it is 3136,
    ; which is off a 1024-wide map and therefore transparent everywhere.
    lda #$40
    sta $210D
    lda #$0C
    sta $210D
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c12-direct-colour-zero-is-transparent — C12.02
; Direct colour mode with a non-black backdrop. Pixel value 0 is transparent in every mode, direct colour included, so pure black is not reachable through it — the backdrop shows instead. A core that treats direct colour as an unconditional RGB decode renders black where the hardware renders the backdrop, which is exactly the case a picture separates and a register read cannot.
.proc scene_c12_direct_colour_zero_is_transparent
    .a16
    .i16
    sep #$20
    .a8
    lda #$03
    sta $2105         ; BGMODE 3 — BG1 is 8bpp, which direct colour needs
    lda #(MAP_BASE >> 8)
    sta $2107
    jsr scene_low_tiles
    sep #$20
    .a8
    lda #$01
    sta $2130         ; CGWSEL bit 0: direct colour for the 8bpp layer
    ; A backdrop that is obviously not black, so a transparent pixel is legible as one.
    stz $2121
    lda #$1F
    sta $2122         ; CGRAM 0 low: red = 31
    stz $2122
    lda #$01
    sta $212C         ; BG1 on the main screen
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c11-mode7-rotate-scale — C11.01
; A rotation-and-scale matrix (A=D=$00B5, B=-$00B5, C=$00B5 — roughly 45 degrees at 0.7x) about a centre of (128,112). Evidence for the affine transform itself: a core that transposes the matrix, drops the centre subtraction, or applies the offsets in the wrong order produces a picture that is recognisably wrong rather than subtly so, because the tile grid makes the axes visible.
.proc scene_c11_mode7_rotate_scale
    .a16
    .i16
    sep #$20
    .a8
    lda #$07
    sta $2105
    jsr scene_mode7_vram
    sep #$20
    .a8
    stz $211A
    lda #$B5
    sta $211B
    stz $211B         ; M7A = $00B5
    lda #$4B
    sta $211C
    lda #$FF
    sta $211C         ; M7B = -$00B5
    lda #$B5
    sta $211D
    stz $211D         ; M7C = $00B5
    lda #$B5
    sta $211E
    stz $211E         ; M7D = $00B5
    lda #128
    sta $211F
    stz $211F         ; M7X = 128
    lda #112
    sta $2120
    stz $2120         ; M7Y = 112
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c11-screen-over-wrap — C11.04
; Zoomed out 8x (A=D=$0800) so the 1024x1024 map is smaller than the screen, with M7SEL bit 7 clear: the map REPEATS outside its bounds. The first of three scenes that differ only in M7SEL's top two bits, which is what makes the screen-over field legible — each mode is defined by how it differs from the other two.
.proc scene_c11_screen_over_wrap
    .a16
    .i16
    sep #$20
    .a8
    lda #$07
    sta $2105
    jsr scene_mode7_vram
    sep #$20
    .a8
    stz $211A         ; M7SEL bit 7 clear: wrap
    stz $211B
    lda #$08
    sta $211B         ; M7A = $0800 — 8x zoom out, so the map edge is on screen
    stz $211C
    stz $211C
    stz $211D
    stz $211D
    stz $211E
    sta $211E         ; M7D = $0800
    stz $211F
    stz $211F
    stz $2120
    stz $2120
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c11-screen-over-transparent — C11.04
; The same zoom with M7SEL bit 7 set and bit 6 clear: outside the map is TRANSPARENT, so the backdrop shows through and the map appears as a single tile floating on it. Must not hash the same as the wrap scene.
.proc scene_c11_screen_over_transparent
    .a16
    .i16
    sep #$20
    .a8
    lda #$07
    sta $2105
    jsr scene_mode7_vram
    sep #$20
    .a8
    lda #$80
    sta $211A         ; M7SEL: screen-over = transparent
    stz $211B
    lda #$08
    sta $211B
    stz $211C
    stz $211C
    stz $211D
    stz $211D
    stz $211E
    sta $211E
    stz $211F
    stz $211F
    stz $2120
    stz $2120
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c11-screen-over-char0 — C11.04
; The same zoom again with both M7SEL top bits set: outside the map every pixel comes from character 0 instead. The third of the trio — and the one most likely to be missing, because a core that implements only wrap and transparent renders this identically to one of them.
.proc scene_c11_screen_over_char0
    .a16
    .i16
    sep #$20
    .a8
    lda #$07
    sta $2105
    jsr scene_mode7_vram
    sep #$20
    .a8
    lda #$C0
    sta $211A         ; M7SEL: screen-over = character 0
    stz $211B
    lda #$08
    sta $211B
    stz $211C
    stz $211C
    stz $211D
    stz $211D
    stz $211E
    sta $211E
    stz $211F
    stz $211F
    stz $2120
    stz $2120
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c11-mode7-screen-flip — C11.01
; The identity matrix with M7SEL's horizontal and vertical flip bits both set. The flip is applied to the SCREEN coordinate before the transform, not to the result, so it is not the same as negating the matrix — a core that implements it as a negation gets the centre wrong and the picture lands somewhere else entirely.
.proc scene_c11_mode7_screen_flip
    .a16
    .i16
    sep #$20
    .a8
    lda #$07
    sta $2105
    jsr scene_mode7_vram
    sep #$20
    .a8
    lda #$03
    sta $211A         ; M7SEL bits 0 and 1: flip both axes
    stz $211B
    lda #$01
    sta $211B
    stz $211C
    stz $211C
    stz $211D
    stz $211D
    stz $211E
    sta $211E
    stz $211F
    stz $211F
    stz $2120
    stz $2120
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c11-extbg-priority-split — C11.09
; EXTBG on (SETINI bit 6) with both BG1 and BG2 enabled. Mode 7 has one background, and EXTBG splits it in two by the pixel's high bit: pixels 0-127 become BG1, 128-255 become BG2 at its own priority. The character gradient runs through both halves, so the split appears as alternating bands rather than as a subtle ordering change.
.proc scene_c11_extbg_priority_split
    .a16
    .i16
    sep #$20
    .a8
    lda #$07
    sta $2105
    jsr scene_mode7_vram
    sep #$20
    .a8
    lda #$40
    sta $2133         ; SETINI bit 6: EXTBG
    stz $211A
    stz $211B
    lda #$01
    sta $211B
    stz $211C
    stz $211C
    stz $211D
    stz $211D
    stz $211E
    sta $211E
    stz $211F
    stz $211F
    stz $2120
    stz $2120
    lda #$03
    sta $212C         ; BG1 + BG2 — the two halves of the one Mode 7 layer
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c11-mode7-direct-colour — C11.10,C12.03
; Direct colour on Mode 7 BG1, where it IS available (unlike EXTBG's BG2). The 8-bit pixel supplies the colour itself, so the canvas's 256 palette entries stop mattering — which is exactly what distinguishes this from `c11-mode7-identity`, the same scene with CGRAM still in the path.
.proc scene_c11_mode7_direct_colour
    .a16
    .i16
    sep #$20
    .a8
    lda #$07
    sta $2105
    jsr scene_mode7_vram
    sep #$20
    .a8
    lda #$01
    sta $2130         ; CGWSEL bit 0: direct colour
    stz $211A
    stz $211B
    lda #$01
    sta $211B
    stz $211C
    stz $211C
    stz $211D
    stz $211D
    stz $211E
    sta $211E
    stz $211F
    stz $211F
    stz $2120
    stz $2120
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c10-mode7-mosaic — C10.05
; Mosaic size 4 applied in Mode 7. The claim is that Mode 7 takes its vertical and horizontal mosaic from different bits than a tiled mode does, so this is read against `c10-mosaic-4x`: same MOSAIC register value, different mode, and the block structure must appear in both.
.proc scene_c10_mode7_mosaic
    .a16
    .i16
    sep #$20
    .a8
    lda #$07
    sta $2105
    jsr scene_mode7_vram
    sep #$20
    .a8
    lda #$31
    sta $2106         ; MOSAIC: size 4, enabled on BG1
    stz $211A
    stz $211B
    lda #$01
    sta $211B
    stz $211C
    stz $211C
    stz $211D
    stz $211D
    stz $211E
    sta $211E
    stz $211F
    stz $211F
    stz $2120
    stz $2120
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c11-mode7-window — C11.11
; A window clipping Mode 7's BG1 on the main screen, bounds 64..191. Windows act in SCREEN space, so the clipped band is a straight vertical edge regardless of how the map underneath is rotated — this scene rotates it, so a core that applies the window in map space produces a diagonal edge instead.
.proc scene_c11_mode7_window
    .a16
    .i16
    sep #$20
    .a8
    lda #$07
    sta $2105
    jsr scene_mode7_vram
    sep #$20
    .a8
    stz $211A
    lda #$B5
    sta $211B
    stz $211B         ; M7A = $00B5 — the same matrix as c11-mode7-rotate-scale, so the
    lda #$4B
    sta $211C
    lda #$FF
    sta $211C         ; M7B = -$00B5   two scenes differ only by the window
    lda #$B5
    sta $211D
    stz $211D         ; M7C = $00B5
    lda #$B5
    sta $211E
    stz $211E         ; M7D = $00B5
    lda #128
    sta $211F
    stz $211F         ; M7X = 128
    lda #112
    sta $2120
    stz $2120         ; M7Y = 112
    lda #$02
    sta $2123         ; W12SEL: BG1 uses window 1
    lda #64
    sta $2126
    lda #191
    sta $2127
    lda #$01
    sta $212E         ; TMW: clip BG1
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c4-shared-scroll-latch — C4.02,C4.03
; One byte written to BG1HOFS ($210D), then one byte to BG1VOFS ($210E). The scroll registers share a SINGLE `Prev` latch across all four backgrounds and both axes, so the V scroll comes out built from both writes: (second << 8) | first. A core with a per-register latch builds it from that register's own history instead, and the picture lands 128 rows away — not a subtlety, a different screen.
.proc scene_c4_shared_scroll_latch
    .a16
    .i16
    sep #$20
    .a8
    stz $2105         ; BGMODE 0
    lda #(MAP_BASE >> 8)
    sta $2107
    stz $210B
    lda #$80
    sta $210D         ; ONE write to the H register: this only loads the shared latch
    lda #$01
    sta $210E         ; ONE write to the V register: (01 << 8) | 80 = $0180 if shared
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c4-hofs-keeps-low-three-bits — C4.01
; The H scroll's write-twice formula is not the V scroll's: it masks the previous byte's low three bits away and takes them from the register's own current value instead. Writing $47 then $00 therefore scrolls by $40, not $47. Paired with `c4-shared-scroll-latch`, which shows the V register keeping all eight bits of the same latch, the two make the asymmetry visible rather than merely stated.
.proc scene_c4_hofs_keeps_low_three_bits
    .a16
    .i16
    sep #$20
    .a8
    stz $2105
    lda #(MAP_BASE >> 8)
    sta $2107
    stz $210B
    lda #$47
    sta $210D
    lda #$00
    sta $210D         ; BG1HOFS: the $7 in $47 is masked off by the H formula
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c4-210d-drives-mode7-scroll — C4.04,C4.05
; The same $210D writes in Mode 7. That register drives BOTH BG1HOFS and M7HOFS, and the Mode 7 side latches through its own 13-bit path rather than the background one — so the picture moves, and by a different amount than the tiled case. A core that treats $210D as belonging to the backgrounds alone leaves Mode 7 unscrolled.
.proc scene_c4_210d_drives_mode7_scroll
    .a16
    .i16
    sep #$20
    .a8
    lda #$07
    sta $2105         ; BGMODE 7
    jsr scene_mode7_vram
    sep #$20
    .a8
    stz $211A
    stz $211B
    lda #$01
    sta $211B         ; M7A = $0100
    stz $211C
    stz $211C
    stz $211D
    stz $211D
    stz $211E
    sta $211E         ; M7D = $0100
    stz $211F
    stz $211F
    stz $2120
    stz $2120
    lda #$47
    sta $210D
    lda #$00
    sta $210D         ; drives M7HOFS as well as BG1HOFS
    lda #$01
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c7-lower-index-on-top — C7.15
; Two overlapping sprites in different palettes, the lower OAM index second in the write order. Sprite priority among sprites is decided by OAM index alone — lower is always in front — regardless of the order they were written or their attribute priority bits. Writing them in the opposite order to the expected result is the point: a core that draws in write order gets this exactly backwards.
.proc scene_c7_lower_index_on_top
    .a16
    .i16
    sep #$20
    .a8
    stz $2105         ; BGMODE 0
    jsr scene_oam_reset
    sep #$20
    .a8
    ; --- sprite 1 first: palette 1, offset down-right ---
    rep #$30
    .a16
    .i16
    ldx #$0004        ; OAM byte 4 = sprite 1
    stx $2102
    sep #$20
    .a8
    lda #100
    sta $2104         ; X
    lda #100
    sta $2104         ; Y
    lda #$10
    sta $2104         ; tile $10 — inside the font AND printable at 4bpp
    lda #$32
    sta $2104         ; attr: palette 1, priority 3
    ; --- sprite 0 second: palette 3, overlapping ---
    rep #$30
    .a16
    .i16
    ldx #$0000
    stx $2102
    sep #$20
    .a8
    lda #96
    sta $2104
    lda #96
    sta $2104
    lda #$10
    sta $2104
    lda #$36
    sta $2104         ; attr: palette 3, same priority
    lda #$10
    sta $212C         ; OBJ on the main screen
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c8-obj-math-palettes-4-7 — C8.01
; Two identical sprites side by side, one in palette 2 and one in palette 6, with colour math enabled for OBJ against the fixed colour. Only the palette-6 sprite blends: sprite colour math applies to palettes 4-7 and to nothing else. It is an errata rather than a rule anyone would guess, and a core that applies the maths to every sprite blends both — a picture that looks perfectly reasonable until it is compared with one that is right.
.proc scene_c8_obj_math_palettes_4_7
    .a16
    .i16
    sep #$20
    .a8
    stz $2105         ; BGMODE 0
    jsr scene_oam_reset
    sep #$20
    .a8
    stz $2101         ; OBJSEL: 8x8 / 16x16, name base word $0000 (the font)
    rep #$30
    .a16
    .i16
    ldx #$0000
    stx $2102
    sep #$20
    .a8
    lda #60
    sta $2104         ; sprite 0 X
    lda #90
    sta $2104         ; sprite 0 Y
    lda #$10
    sta $2104         ; tile $10 — printable at 4bpp
    lda #$34
    sta $2104         ; attr: palette 2, priority 3 — below the math threshold
    lda #140
    sta $2104         ; sprite 1 X
    lda #90
    sta $2104         ; sprite 1 Y
    lda #$10
    sta $2104         ; the same tile, so only the palette differs
    lda #$3C
    sta $2104         ; attr: palette 6, priority 3 — inside the math range
    lda #$10
    sta $212C         ; OBJ on the main screen
    lda #$02
    sta $2130         ; CGWSEL: the subscreen is the fixed colour
    lda #$10
    sta $2131         ; CGADSUB: add, applied to OBJ only
    lda #$9F
    sta $2132         ; COLDATA: blue = 31
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c7-objsel-size-6 — C7.10
; OBJSEL size pair 6, which no official document lists: 16x32 small, 32x64 large. Two sprites side by side, one of each, so the picture states both halves of the pair at once. The pairs above 5 are the only ones whose members are not square, and a core that stops its table at 5 — or repeats an earlier pair to fill the gap — draws squares here.
.proc scene_c7_objsel_size_6
    .a16
    .i16
    sep #$20
    .a8
    stz $2105         ; BGMODE 0
    jsr scene_oam_reset
    sep #$20
    .a8
    lda #$C0
    sta $2101         ; OBJSEL pair 6, name base word $0000
    rep #$30
    .a16
    .i16
    ldx #$0000
    stx $2102
    sep #$20
    .a8
    lda #40
    sta $2104         ; sprite 0 X
    lda #60
    sta $2104         ; sprite 0 Y
    lda #$10
    sta $2104         ; tile $10 — printable at 4bpp
    lda #$30
    sta $2104         ; attr: palette 0, priority 3
    lda #120
    sta $2104         ; sprite 1 X
    lda #60
    sta $2104         ; sprite 1 Y
    lda #$10
    sta $2104
    lda #$30
    sta $2104
    rep #$30
    .a16
    .i16
    ldx #$0100
    stx $2102         ; the high table
    sep #$20
    .a8
    lda #$08
    sta $2104         ; sprite 0 small (16x32), sprite 1 large (32x64)
    lda #$10
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c7-objsel-size-7 — C7.10
; OBJSEL size pair 7 — the other undocumented one: 16x32 small, 32x32 large. The same two sprites as the pair-6 scene with a single OBJSEL bit changed, so the two scenes differ by exactly the large sprite's height and nothing else. Pairs 6 and 7 share a small member, which is why they have to be told apart by the large one.
.proc scene_c7_objsel_size_7
    .a16
    .i16
    sep #$20
    .a8
    stz $2105
    jsr scene_oam_reset
    sep #$20
    .a8
    lda #$E0
    sta $2101         ; OBJSEL pair 7, name base word $0000
    rep #$30
    .a16
    .i16
    ldx #$0000
    stx $2102
    sep #$20
    .a8
    lda #40
    sta $2104
    lda #60
    sta $2104
    lda #$10
    sta $2104
    lda #$30
    sta $2104
    lda #120
    sta $2104
    lda #60
    sta $2104
    lda #$10
    sta $2104
    lda #$30
    sta $2104
    rep #$30
    .a16
    .i16
    ldx #$0100
    stx $2102
    sep #$20
    .a8
    lda #$08
    sta $2104         ; sprite 0 small (16x32), sprite 1 large (32x32)
    lda #$10
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c7-vflip-tall-halves — C7.13
; A 16x32 sprite with the V-flip attribute set. The errata: each 16x16 half flips INDEPENDENTLY rather than the sprite flipping as a whole, so the two halves swap their internal contents but stay in place relative to each other. A core that flips the whole sprite produces a picture that is upside-down in a different way — same pixels, different arrangement, which a hash separates and an eye might not. Re-blessed once: this scene originally selected OBJSEL pair 3 and set the sprite's size bit, which is 32x32 — a square sprite, on which the errata says nothing. A tall size needs pair 6 or 7, whose SMALL member is 16x32.
.proc scene_c7_vflip_tall_halves
    .a16
    .i16
    sep #$20
    .a8
    stz $2105
    jsr scene_oam_reset
    sep #$20
    .a8
    lda #$C0
    sta $2101         ; OBJSEL size pair 6: 16x32 / 32x64, name base word $0000
    rep #$30
    .a16
    .i16
    ldx #$0000
    stx $2102
    sep #$20
    .a8
    lda #100
    sta $2104         ; X
    lda #80
    sta $2104         ; Y
    lda #$10
    sta $2104         ; tile $10
    lda #$B0
    sta $2104         ; attr: V-flip set, palette 0, priority 3
    ; high table: sprite 0 size bit set -> the LARGE size of the pair (16x32)
    rep #$30
    .a16
    .i16
    ldx #$0100
    stx $2102         ; OAMADD = $100 words = the high table
    sep #$20
    .a8
    lda #$00
    sta $2104         ; sprite 0: X bit 8 clear, size bit CLEAR -> the small 16x32
    lda #$10
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

; c7-64px-wraps-bottom-to-top — C7.14
; A 64-pixel-tall sprite placed near the bottom of a 224-line display. It wraps: the part that would fall past line 224 reappears at the top of the screen. A core that clips instead simply loses those rows, which is the same picture minus a band — so this is read against `c7-vflip-tall-halves`, where nothing wraps.
.proc scene_c7_64px_wraps_bottom_to_top
    .a16
    .i16
    sep #$20
    .a8
    stz $2105
    jsr scene_oam_reset
    sep #$20
    .a8
    lda #$A0
    sta $2101         ; OBJSEL size pair 5: 32x32 / 64x64
    rep #$30
    .a16
    .i16
    ldx #$0000
    stx $2102
    sep #$20
    .a8
    lda #120
    sta $2104         ; X
    lda #200
    sta $2104         ; Y = 200: 64 tall runs 24 rows past the bottom
    lda #$10
    sta $2104
    lda #$30
    sta $2104         ; attr: palette 0, priority 3
    rep #$30
    .a16
    .i16
    ldx #$0100
    stx $2102
    sep #$20
    .a8
    lda #$02
    sta $2104         ; sprite 0 takes the large size of the pair (64x64)
    lda #$10
    sta $212C
    lda #$0F
    sta $2100
    rep #$30
    .a16
    .i16
    rts
.endproc

.segment "CATALOG"
.export _scene_count
.export _scene_entries
_scene_count:
    .word 49
_scene_entries:
    .addr scene_c5_mode1_bg_priority
    .addr scene_c8_fixed_colour_add
    .addr scene_c10_mosaic_4x
    .addr scene_c5_mode0_four_bg_priority
    .addr scene_c5_mode0_palette_segregation
    .addr scene_c5_mode3_8bpp
    .addr scene_c5_tilemap_flip_bits
    .addr scene_c5_16x16_tiles
    .addr scene_c8_subtract_mode
    .addr scene_c8_clamp_no_wrap
    .addr scene_c8_half_ignored_on_fixed_backdrop
    .addr scene_c8_window_bounds_inclusive
    .addr scene_c8_window_left_gt_right_empty
    .addr scene_c8_window_inverted_empty_is_full
    .addr scene_c8_both_windows_disabled_empty
    .addr scene_c8_window_logic_xor
    .addr scene_c10_mosaic_screen_anchored
    .addr scene_c12_direct_colour_mode3
    .addr scene_c5_mode2_plain
    .addr scene_c6_opt_v_alternating_columns
    .addr scene_c6_opt_v_replaces_vofs
    .addr scene_c6_opt_h_keeps_fine_scroll
    .addr scene_c6_opt_enable_bit_bg1
    .addr scene_c6_opt_enable_bit_bg2
    .addr scene_c6_mode4_h_vs_v_select
    .addr scene_c11_mode7_identity
    .addr scene_c5_mode4_two_layers
    .addr scene_c5_bgsc_64x32_second_map_right
    .addr scene_c5_mode7_ignores_bgsc
    .addr scene_c11_org_13bit_mask
    .addr scene_c12_direct_colour_zero_is_transparent
    .addr scene_c11_mode7_rotate_scale
    .addr scene_c11_screen_over_wrap
    .addr scene_c11_screen_over_transparent
    .addr scene_c11_screen_over_char0
    .addr scene_c11_mode7_screen_flip
    .addr scene_c11_extbg_priority_split
    .addr scene_c11_mode7_direct_colour
    .addr scene_c10_mode7_mosaic
    .addr scene_c11_mode7_window
    .addr scene_c4_shared_scroll_latch
    .addr scene_c4_hofs_keeps_low_three_bits
    .addr scene_c4_210d_drives_mode7_scroll
    .addr scene_c7_lower_index_on_top
    .addr scene_c8_obj_math_palettes_4_7
    .addr scene_c7_objsel_size_6
    .addr scene_c7_objsel_size_7
    .addr scene_c7_vflip_tall_halves
    .addr scene_c7_64px_wraps_bottom_to_top
