; GENERATED by accuracysnes-gen — do not edit by hand.
; Source of truth: tests/roms/AccuracySNES/gen/src/tests/
.p816
CATALOG_IMPL = 1
.include "runtime.inc"

.segment "TESTS"

.segment "TESTSE"

.segment "TESTSC"

.segment "TESTSD"

.segment "TESTSG"

; G1.15 — HiROM decode
; provenance: Documented (SNESdev Wiki, memory map (HiROM: banks $C0-$FF linear, $00-$3F:$8000-$FFFF window, $40-$7D mirror $C0-$FD); fullsnes)
.proc test_g1_15
    .a16
    .i16
    sep #$20
    .a8
    ; The header must read as HiROM.
    lda f:$00FFD5
    cmp #$21
    beq :+
    jmp @fail1
  :
    ; HiROM maps the $00:8000-$FFFF window and the $C0-$FF linear banks to the same ROM. The
    ; title's first byte at $FFC0 is a fixed landmark in the upper half, reachable both ways.
    lda f:$00FFC0
    sta f:$7E0120       ; the byte as seen through the $00:8000 window
    lda f:$C0FFC0
    cmp f:$7E0120
    beq :+
    jmp @fail2
  :
    ; The $40-$7D banks mirror $C0-$FD, so $40:FFC0 must read the same byte.
    lda f:$40FFC0
    cmp f:$7E0120
    beq :+
    jmp @fail3
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jml test_restore
@fail1:
    ; the map-mode byte at $FFD5 is not $21 (HiROM, SlowROM), so the emulator did not select the HiROM board for this image
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jml test_restore
@fail2:
    ; $00:FFC0 (the HiROM window) and $C0:FFC0 (the linear high bank) returned different bytes, so the two views do not decode to the same ROM offset — the HiROM decode is wrong
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jml test_restore
@fail3:
    ; $40:FFC0 does not match $C0:FFC0 — the $40-$7D HiROM bank mirror of $C0-$FD is wrong
    sep #$20
    .a8
    lda #$06
    sta f:$7EE010
    jml test_restore
.endproc

; G1.17 — HiROM SRAM window
; provenance: Documented (SNESdev Wiki, memory map (HiROM SRAM at $20-$3F:$6000-$7FFF, mirrored $A0-$BF); fullsnes)
.proc test_g1_17
    .a16
    .i16
    sep #$20
    .a8
    ; HiROM battery SRAM is at $20-$3F:$6000-$7FFF. Write two distinctive bytes and read back.
    lda #$5A
    sta f:$206000
    lda #$A5
    sta f:$206001
    lda f:$206000
    cmp #$5A
    beq :+
    jmp @fail1
  :
    lda f:$206001
    cmp #$A5
    beq :+
    jmp @fail2
  :
    ; The $A0-$BF banks mirror $20-$3F, so $A0:6000 must read the same SRAM byte.
    lda f:$A06000
    cmp #$5A
    beq :+
    jmp @fail3
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jml test_restore
@fail1:
    ; SRAM at $20:6000 did not read back the value just written — the HiROM battery-SRAM window ($20-$3F:$6000-$7FFF) is not mapped as writable RAM
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jml test_restore
@fail2:
    ; SRAM at $20:6001 did not read back — the SRAM window is not backed by persistent RAM across the two accesses
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jml test_restore
@fail3:
    ; $A0:6000 does not mirror $20:6000 — the $A0-$BF HiROM SRAM mirror is wrong
    sep #$20
    .a8
    lda #$06
    sta f:$7EE010
    jml test_restore
.endproc

.segment "TESTSG"

.segment "CATALOG"
.export _test_count
.export _test_entries
.export _test_names
.export _test_flags

_test_count:
    .word 2

; Entry points, 24-bit: test bodies no longer all live in bank $00.
_test_entries:
    .faraddr test_g1_15
    .faraddr test_g1_17

; Per-test flags: bit0 = scores toward the pass rate, bit1 = golden-vector.
_test_flags:
    .byte $01   ; G1.15
    .byte $01   ; G1.17

; Menu labels, each a length-prefixed ASCII string.
_test_names:
    .addr @n_g1_15
    .addr @n_g1_17
@n_g1_15:
    .byte 12
    .byte "HiROM decode"
@n_g1_17:
    .byte 17
    .byte "HiROM SRAM window"
