; GENERATED by accuracysnes-gen — do not edit by hand.
; Source of truth: tests/roms/AccuracySNES/gen/src/tests/
.p816
CATALOG_IMPL = 1
.include "runtime.inc"

.segment "TESTS"

; A1.01 — XCE clears XH/YH
; provenance: Documented (SNESdev Errata, 65C816 section)
.proc test_a1_01
    .a16
    .i16
    ; Entering emulation forces x=1, which zeroes the high bytes of X and Y.
    rep #$30
    .a16
    .i16
    ldx #$1234
    ldy #$5678
    sec
    xce               ; -> emulation
    .a8
    .i8
    clc
    xce               ; -> native (m/x stay 1: still 8-bit)
    .a8
    .i8
    rep #$30
    .a16
    .i16
    cpx #$0034
    beq :+
    jmp @fail1
  :
    cpy #$0078
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; XH not cleared by entering emulation mode
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; YH not cleared by entering emulation mode
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; A1.02 — SEP #$10 clears XH/YH
; provenance: Documented (SNESdev Errata, 65C816 section)
.proc test_a1_02
    .a16
    .i16
    ; SEP #$10 sets x=1 -> XH/YH are destroyed, not merely hidden.
    rep #$30
    .a16
    .i16
    ldx #$1234
    ldy #$5678
    sep #$10
    .i8
    rep #$10
    .i16
    cpx #$0034
    beq :+
    jmp @fail1
  :
    cpy #$0078
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; XH survived SEP #$10 (must be cleared, not masked)
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; YH survived SEP #$10 (must be cleared, not masked)
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; A1.03 — E=1 forces SH=$01
; provenance: Documented (6502.org 65c816opcodes; WDC datasheet)
.proc test_a1_03
    .a16
    .i16
    ; E=1 confines the stack to page 1: SH is forced to $01, SL is untouched.
    rep #$30
    .a16
    .i16
    lda #$05AB
    tcs
    sec
    xce               ; -> emulation
    .a8
    .i8
    clc
    xce               ; -> native (m/x stay 1: still 8-bit)
    .a8
    .i8
    rep #$30
    .a16
    .i16
    tsc
    cmp #$01AB
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; SH not forced to $01 on entering emulation mode
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A1.04 — TXS in emu -> $01FF
; provenance: Documented (6502.org 65c816opcodes)
.proc test_a1_04
    .a16
    .i16
    ; TXS in emulation: 8-bit X into SL, SH stays $01.
    sec
    xce               ; -> emulation
    .a8
    .i8
    ldx #$FF
    txs
    clc
    xce               ; -> native (m/x stay 1: still 8-bit)
    .a8
    .i8
    rep #$30
    .a16
    .i16
    tsc
    cmp #$01FF
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; TXS in emulation did not keep SH=$01
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A1.05 — TCS in emu -> $0134
; provenance: Documented (6502.org 65c816opcodes)
.proc test_a1_05
    .a16
    .i16
    ; TCS is always 16-bit; in emulation SH is then forced back to $01.
    rep #$30
    .a16
    .i16
    lda #$1234
    ; C keeps $1234 internally even though the 8-bit view shows only $34.
    sec
    xce               ; -> emulation
    .a8
    .i8
    tcs               ; S = $0134
    clc
    xce               ; -> native (m/x stay 1: still 8-bit)
    .a8
    .i8
    rep #$30
    .a16
    .i16
    tsc
    cmp #$0134
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; TCS in emulation did not yield $0134
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A2.01 — d,X never crosses bank
; provenance: Documented (superfamicom.org 65816 reference, worked example)
.proc test_a2_01
    .a16
    .i16
    ; D=$FFFF, X=$8000, lda $06,X  ->  $FFFF+$06+$8000 = $18005, wraps to $00:8005.
    ; A bank-crossing implementation would read $01:8005 instead (a different ROM bank).
    rep #$30
    .a16
    .i16
    lda #$FFFF
    tcd
    ldx #$8000
    sep #$20          ; 8-bit A for the byte compare
    .a8
    lda $06,X
    cmp #$A0
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; d,X crossed into bank $01 instead of wrapping within bank $00
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A2.02 — E=1 DL=$00 page wraps
; provenance: Documented (superfamicom.org 65816 reference)
.proc test_a2_02
    .a16
    .i16
    ; E=1, DL=$00: lda $FF,X with X=$01 wraps to D+$00, not D+$100.
    rep #$30
    .a16
    .i16
    lda #$0000
    tcd               ; D=$0000, so DL=$00
    ; Seed the two candidate addresses through a long store (DBR-independent).
    sep #$20
    .a8
    lda #$5A
    sta f:$7E0000     ; the wrapped target
    lda #$A5
    sta f:$7E0100     ; the non-wrapped target
    rep #$30
    .a16
    .i16
    ldx #$0001
    sec
    xce               ; -> emulation
    .a8
    .i8
    lda $FF,X         ; 8-bit in emulation
    clc
    xce               ; -> native (m/x stay 1: still 8-bit)
    .a8
    .i8
    cmp #$5A
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; emulation DL=$00 did not page-wrap the direct-page index
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A2.03 — E=1 DL!=$00 carries
; provenance: Documented (superfamicom.org 65816 reference)
.proc test_a2_03
    .a16
    .i16
    ; E=1, DL=$10: the page-wrap special case does not apply; the index carries.
    rep #$30
    .a16
    .i16
    sep #$20
    .a8
    lda #$3C
    sta f:$7E0110     ; D+$FF+$01 = $0010+$0100 = $0110
    lda #$C3
    sta f:$7E0010     ; the address a wrongly-wrapping core would hit
    rep #$30
    .a16
    .i16
    lda #$0010
    tcd               ; D=$0010, DL=$10 (non-zero)
    ldx #$0001
    sec
    xce               ; -> emulation
    .a8
    .i8
    lda $FF,X
    clc
    xce               ; -> native (m/x stay 1: still 8-bit)
    .a8
    .i8
    cmp #$3C
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; emulation DL!=$00 wrongly page-wrapped the direct-page index
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A2.04 — Native always carries
; provenance: Documented (superfamicom.org 65816 reference)
.proc test_a2_04
    .a16
    .i16
    ; E=0, D=$0000: lda $FF,X with X=$01 reaches $0100 — no 6502-style page wrap.
    rep #$30
    .a16
    .i16
    sep #$20
    .a8
    lda #$77
    sta f:$7E0100
    lda #$88
    sta f:$7E0000
    rep #$30
    .a16
    .i16
    lda #$0000
    tcd
    ldx #$0001
    sep #$20
    .a8
    lda $FF,X
    cmp #$77
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; native mode page-wrapped the direct-page index (it must carry)
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A2.05 — [dp] never page-wraps
; provenance: Documented (superfamicom.org 65816 reference; WDC datasheet)
.proc test_a2_05
    .a16
    .i16
    ; E=1, D=$0000, [dp] with dp=$FF: pointer bytes come from $FF, $0100, $0101 —
    ; the 6502 page-wrap does NOT apply to the 65816's new addressing modes.
    rep #$30
    .a16
    .i16
    ; Build a 24-bit pointer to $7E1234 across the page boundary.
    sep #$20
    .a8
    lda #$34
    sta f:$7E00FF
    lda #$12
    sta f:$7E0100
    lda #$7E
    sta f:$7E0101
    lda #$6B
    sta f:$7E1234     ; the value a correct core will fetch
    rep #$30
    .a16
    .i16
    lda #$0000
    tcd
    sep #$20
    .a8
    lda [$FF]
    cmp #$6B
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; [dp] pointer fetch page-wrapped (new modes must not)
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A3.01 — E=1 stack wraps pg1
; provenance: Documented (WDC datasheet; 6502.org 65c816opcodes)
.proc test_a3_01
    .a16
    .i16
    ; E=1, S=$0100: PHA writes $01:0100 and S wraps to $01FF.
    rep #$30
    .a16
    .i16
    lda #$0100
    tcs
    sec
    xce               ; -> emulation
    .a8
    .i8
    lda #$9D
    pha               ; writes $00:0100, S -> $01FF
    clc
    xce               ; -> native (m/x stay 1: still 8-bit)
    .a8
    .i8
    rep #$30
    .a16
    .i16
    tsc
    cmp #$01FF
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda f:$7E0100
    ; Note: $00:0100 is the low-WRAM mirror of $7E:0100.
    cmp #$9D
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; emulation stack did not wrap within page 1
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; PHA did not write the byte at $0100
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; A3.02 — PEA escapes page 1
; provenance: Documented (WDC datasheet; hardware-confirmed per superfamicom.org)
.proc test_a3_02
    .a16
    .i16
    ; E=1, S=$0100, PEA $1234: writes $00:0100 and $00:00FF, S -> $01FE.
    ; $01FF must be left untouched — proof the push escaped page 1.
    rep #$30
    .a16
    .i16
    sep #$20
    .a8
    lda #$EE
    sta f:$7E01FF     ; sentinel that must survive
    rep #$30
    .a16
    .i16
    lda #$0100
    tcs
    sec
    xce               ; -> emulation
    .a8
    .i8
    pea $1234
    clc
    xce               ; -> native (m/x stay 1: still 8-bit)
    .a8
    .i8
    rep #$30
    .a16
    .i16
    tsc
    cmp #$01FE
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda f:$7E01FF
    cmp #$EE
    beq :+
    jmp @fail2
  :
    lda f:$7E0100
    cmp #$12
    beq :+
    jmp @fail3
  :
    lda f:$7E00FF
    cmp #$34
    beq :+
    jmp @fail4
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; PEA in emulation did not leave S at $01FE
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; PEA wrongly wrapped into page 1 and clobbered $01FF
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
@fail3:
    ; PEA high byte not written to $0100
    sep #$20
    .a8
    lda #$06
    sta f:$7EE010
    jmp test_restore
@fail4:
    ; PEA low byte not written to $00FF (it must escape page 1)
    sep #$20
    .a8
    lda #$08
    sta f:$7EE010
    jmp test_restore
.endproc

; A3.03 — PLD escapes, PLY not
; provenance: Documented (WDC datasheet; superfamicom.org escape list)
.proc test_a3_03
    .a16
    .i16
    ; E=1, S=$01FF. PLD (new) pulls from $0200/$0201; PLY (old) pulls from $0100.
    ; This pair is the cleanest test of the emulation-mode stack-confinement rule.
    rep #$30
    .a16
    .i16
    sep #$20
    .a8
    lda #$AB
    sta f:$7E0200
    lda #$CD
    sta f:$7E0201
    lda #$5E
    sta f:$7E0100
    rep #$30
    .a16
    .i16
    ; --- PLD: must escape ---
    lda #$01FF
    tcs
    sec
    xce               ; -> emulation
    .a8
    .i8
    pld
    clc
    xce               ; -> native (m/x stay 1: still 8-bit)
    .a8
    .i8
    rep #$30
    .a16
    .i16
    tdc
    cmp #$CDAB
    beq :+
    jmp @fail1
  :
    ; --- PLY: must NOT escape ---
    lda #$0000
    tcd
    lda #$01FF
    tcs
    sec
    xce               ; -> emulation
    .a8
    .i8
    ply               ; 8-bit index in emulation
    clc
    xce               ; -> native (m/x stay 1: still 8-bit)
    .a8
    .i8
    rep #$30
    .a16
    .i16
    cpy #$005E
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; PLD did not pull from $0200/$0201 (it must escape page 1)
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; PLY escaped page 1 (old instructions must wrap to $0100)
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; A3.04 — d,S escapes page 1
; provenance: Documented (WDC datasheet; hardware-confirmed per superfamicom.org)
.proc test_a3_04
    .a16
    .i16
    ; E=1, S=$01FF, lda $02,S -> $00:0201, not a page-1 wrap.
    rep #$30
    .a16
    .i16
    sep #$20
    .a8
    lda #$71
    sta f:$7E0201
    lda #$17
    sta f:$7E0101
    rep #$30
    .a16
    .i16
    lda #$01FF
    tcs
    sec
    xce               ; -> emulation
    .a8
    .i8
    lda $02,S
    clc
    xce               ; -> native (m/x stay 1: still 8-bit)
    .a8
    .i8
    cmp #$71
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; d,S wrapped inside page 1 (it must escape)
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A3.05 — Stack in bank $00
; provenance: Documented (WDC datasheet)
.proc test_a3_05
    .a16
    .i16
    ; Native, S=$0000: PHA writes $00:0000 and S wraps to $FFFF — never bank $01.
    rep #$30
    .a16
    .i16
    sep #$20
    .a8
    lda #$00
    sta f:$7E0000
    rep #$30
    .a16
    .i16
    lda #$0000
    tcs
    sep #$20
    .a8
    lda #$4D
    pha
    rep #$30
    .a16
    .i16
    tsc
    cmp #$FFFF
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda f:$7E0000
    cmp #$4D
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; native stack did not wrap to $FFFF within bank $00
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; push at S=$0000 did not land at $00:0000
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; A4.01 — JMP (a) no page bug
; provenance: Documented (WDC datasheet; SNESdev Errata)
.proc test_a4_01
    .a16
    .i16
    ; JMP ($12FF) must read its high byte from $1300, not wrap to $1200.
    rep #$30
    .a16
    .i16
    ; Point $12FF/$1300 at the success continuation.
    lda #.LOWORD(@landed)
    sta f:$7E12FF
    ; Poison $1200 so a buggy (wrapping) core lands somewhere else.
    sep #$20
    .a8
    lda #$00
    sta f:$7E1200
    rep #$30
    .a16
    .i16
    ; $12FF is reachable as bank-$00 low WRAM mirror.
    jmp ($12FF)
@landed:
    nop
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
.endproc

; A4.02 — JMP (a) ptr bank $00
; provenance: Documented (SNESdev Errata, 65C816 section)
.proc test_a4_02
    .a16
    .i16
    ; The indirect pointer for JMP (a) always comes from bank $00.
    ; Executed from bank $00 here, so this asserts the pointer fetch itself works;
    ; the cross-bank half of the rule is exercised by A4.03.
    rep #$30
    .a16
    .i16
    lda #.LOWORD(@landed)
    sta f:$7E0300
    jmp ($0300)
@landed:
    nop
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
.endproc

; A4.03 — abs,X carries bank
; provenance: Documented (WDC datasheet; superfamicom.org)
.proc test_a4_03
    .a16
    .i16
    ; DBR=$00, X=$8006, lda $FFFF,X  ->  $00FFFF + $8006 = $01:8005,
    ; i.e. the bank $01 signature byte. A core that masked the effective address to
    ; 16 bits would wrap back into bank $00 and read $FF instead.
    rep #$30
    .a16
    .i16
    phk
    plb               ; DBR = $00
    ldx #$8006
    sep #$20
    .a8
    lda $FFFF,X
    cmp #$A1
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; abs,X did not carry into bank $01
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A4.04 — 16-bit abs carries bank
; provenance: Documented (WDC datasheet)
.proc test_a4_04
    .a16
    .i16
    ; DBR=$00, m=0, lda $FFFF: low byte from $00:FFFF, high byte from $01:0000.
    ; $00:FFFF is the emulation-mode IRQ vector high byte; $01:0000 is low WRAM.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda #$C7
    sta f:$7E0000     ; = $01:0000 through the low-WRAM mirror
    rep #$30
    .a16
    .i16
    lda $FFFF
    xba
    and #$00FF
    cmp #$00C7
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; 16-bit absolute read did not carry into the next bank
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A4.05 — long,X carries bank
; provenance: Documented (WDC datasheet)
.proc test_a4_05
    .a16
    .i16
    ; lda $00FFFF,X with X=$8006 -> $00FFFF + $8006 = $01:8005 (bank $01 signature).
    rep #$30
    .a16
    .i16
    ldx #$8006
    sep #$20
    .a8
    lda f:$00FFFF,X
    cmp #$A1
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; long,X did not carry into bank $01
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A5.01 — +1 w when DL != 0
; provenance: Documented (WDC datasheet; superfamicom.org cycle-count tables)
.proc test_a5_01
    .a16
    .i16
    ; Identical instruction, identical operand — only D changes. D=$0000 costs N cycles,
    ; D=$0001 costs N+1, because the penalty keys off DL != 0.
    rep #$30
    .a16
    .i16
    ldx #$0000
    lda #$0000
    tcd               ; DL = $00: no penalty
    jsr hv_begin
    lda $10,x
    lda $10,x
    lda $10,x
    lda $10,x
    lda $10,x
    lda $10,x
    lda $10,x
    lda $10,x
    jsr hv_end
    rep #$30
    .a16
    .i16
    lda f:$7E0048     ; V_H1 = elapsed dots
    sta f:$7E0080     ; baseline
    lda #$0001
    tcd               ; DL = $01: one extra cycle per access
    jsr hv_begin
    lda $10,x
    lda $10,x
    lda $10,x
    lda $10,x
    lda $10,x
    lda $10,x
    lda $10,x
    lda $10,x
    jsr hv_end
    rep #$30
    .a16
    .i16
    lda f:$7E0048     ; V_H1 = elapsed dots
    sec
    sbc f:$7E0080
    cmp #$000A
    bcs :+
    jmp @fail1
  :
    cmp #$000F
    bcc :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; direct-page +1 w penalty (DL != 0) not applied
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A5.02 — +1 p on indexed reads
; provenance: Documented (WDC datasheet; superfamicom.org cycle-count tables)
.proc test_a5_02
    .a16
    .i16
    ; lda $10FF,X with X=$01 crosses a page; with X=$00 it does not.
    ; The index must be 8-BIT: with a 16-bit index the cycle is unconditional, so the two
    ; measurements would be identical and the test would prove nothing.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$10
    .i8
    ldx #$00
    jsr hv_begin
    lda a:$10FF,x
    lda a:$10FF,x
    lda a:$10FF,x
    lda a:$10FF,x
    lda a:$10FF,x
    lda a:$10FF,x
    lda a:$10FF,x
    lda a:$10FF,x
    jsr hv_end
    rep #$30
    .a16
    .i16
    lda f:$7E0048     ; V_H1 = elapsed dots
    sta f:$7E0080
    sep #$10
    .i8
    ldx #$01          ; now every access crosses into the next page
    jsr hv_begin
    lda a:$10FF,x
    lda a:$10FF,x
    lda a:$10FF,x
    lda a:$10FF,x
    lda a:$10FF,x
    lda a:$10FF,x
    lda a:$10FF,x
    lda a:$10FF,x
    jsr hv_end
    rep #$30
    .a16
    .i16
    lda f:$7E0048     ; V_H1 = elapsed dots
    sec
    sbc f:$7E0080
    cmp #$000A
    bcs :+
    jmp @fail1
  :
    cmp #$000F
    bcc :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; indexed read did not pay the +1 p page-cross penalty
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A5.03 — Stores always pay +1 p
; provenance: Documented (WDC datasheet; superfamicom.org cycle-count tables)
.proc test_a5_03
    .a16
    .i16
    ; sta $10FF,X costs the same whether or not it crosses a page — stores always pay the
    ; cycle, so unlike the load in A5.02 there is no difference to find. Same 8-bit index.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$10
    .i8
    ldx #$00
    jsr hv_begin
    sta a:$10FF,x
    sta a:$10FF,x
    sta a:$10FF,x
    sta a:$10FF,x
    sta a:$10FF,x
    sta a:$10FF,x
    sta a:$10FF,x
    sta a:$10FF,x
    jsr hv_end
    rep #$30
    .a16
    .i16
    lda f:$7E0048     ; V_H1 = elapsed dots
    sta f:$7E0080
    sep #$10
    .i8
    ldx #$01          ; crosses a page, but must cost the same
    jsr hv_begin
    sta a:$10FF,x
    sta a:$10FF,x
    sta a:$10FF,x
    sta a:$10FF,x
    sta a:$10FF,x
    sta a:$10FF,x
    sta a:$10FF,x
    sta a:$10FF,x
    jsr hv_end
    rep #$30
    .a16
    .i16
    lda f:$7E0048     ; V_H1 = elapsed dots
    sec
    sbc f:$7E0080
    cmp #$8000
    bcc :+
    eor #$FFFF
    inc a             ; negate: take the magnitude
  :
    cmp #$0003
    bcc :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; indexed store timing changed with page crossing (it must not)
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A5.04 — Decimal costs no cycles
; provenance: Documented (WDC datasheet)
.proc test_a5_04
    .a16
    .i16
    ; Same ADC, binary vs decimal. On the 65C02 decimal adds a cycle; on the 65816 it does not.
    rep #$30
    .a16
    .i16
    sep #$20
    .a8
    cld
    jsr hv_begin
    clc
    adc #$01
    clc
    adc #$01
    clc
    adc #$01
    clc
    adc #$01
    clc
    adc #$01
    clc
    adc #$01
    clc
    adc #$01
    clc
    adc #$01
    jsr hv_end
    rep #$30
    .a16
    .i16
    lda f:$7E0048     ; V_H1 = elapsed dots
    sta f:$7E0080     ; baseline
    sep #$20
    .a8
    sed
    jsr hv_begin
    clc
    adc #$01
    clc
    adc #$01
    clc
    adc #$01
    clc
    adc #$01
    clc
    adc #$01
    clc
    adc #$01
    clc
    adc #$01
    clc
    adc #$01
    jsr hv_end
    sep #$20
    .a8
    cld               ; leave decimal before any further arithmetic
    rep #$30
    .a16
    .i16
    lda f:$7E0048     ; V_H1 = elapsed dots
    sec
    sbc f:$7E0080
    cmp #$8000
    bcc :+
    eor #$FFFF
    inc a             ; negate: take the magnitude
  :
    cmp #$0003
    bcc :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; decimal mode changed instruction timing (it must not on the 65816)
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A5.05 — 16-bit RMW is +2
; provenance: Documented (WDC datasheet (corrects undisbeliever's table))
.proc test_a5_05
    .a16
    .i16
    ; ASL dp with m=1 vs m=0. The 16-bit form reads and writes an extra byte.
    rep #$30
    .a16
    .i16
    lda #$0000
    tcd
    sep #$20          ; 8-bit accumulator -> 8-bit RMW
    .a8
    jsr hv_begin
    asl $20
    asl $20
    asl $20
    asl $20
    asl $20
    asl $20
    asl $20
    asl $20
    jsr hv_end
    rep #$30
    .a16
    .i16
    lda f:$7E0048     ; V_H1 = elapsed dots
    sta f:$7E0080
    rep #$20          ; 16-bit accumulator -> 16-bit RMW
    .a16
    jsr hv_begin
    asl $20
    asl $20
    asl $20
    asl $20
    asl $20
    asl $20
    asl $20
    asl $20
    jsr hv_end
    rep #$30
    .a16
    .i16
    lda f:$7E0048     ; V_H1 = elapsed dots
    sec
    sbc f:$7E0080
    cmp #$001E
    bcs :+
    jmp @fail1
  :
    cmp #$0023
    bcc :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; 16-bit RMW is not +2 cycles over the 8-bit form
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A5.06 — Taken branch costs +1
; provenance: Documented (WDC datasheet)
.proc test_a5_06
    .a16
    .i16
    ; BCC taken vs not taken, same instruction, same target, one cycle apart.
    rep #$30
    .a16
    .i16
    sec               ; carry set -> BCC never taken
    jsr hv_begin
    bcc *+2
    bcc *+2
    bcc *+2
    bcc *+2
    bcc *+2
    bcc *+2
    bcc *+2
    bcc *+2
    jsr hv_end
    rep #$30
    .a16
    .i16
    lda f:$7E0048     ; V_H1 = elapsed dots
    sta f:$7E0080
    clc               ; carry clear -> BCC always taken
    jsr hv_begin
    bcc *+2
    bcc *+2
    bcc *+2
    bcc *+2
    bcc *+2
    bcc *+2
    bcc *+2
    bcc *+2
    jsr hv_end
    rep #$30
    .a16
    .i16
    lda f:$7E0048     ; V_H1 = elapsed dots
    sec
    sbc f:$7E0080
    cmp #$000A
    bcs :+
    jmp @fail1
  :
    cmp #$000F
    bcc :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; a taken branch did not cost one extra cycle
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A6.01 — BRK vectors natively
; provenance: Documented (WDC datasheet; SNESdev Wiki vectors)
.proc test_a6_01
    .a16
    .i16
    jmp @start
@handler:
    sep #$20
    .a8
    lda #$A5
    sta f:$7E0090     ; prove the handler actually ran
    rep #$30
    .a16
    .i16
    rti
@start:
    rep #$30
    .a16
    .i16
    sep #$20
    .a8
    lda #$00
    sta f:$7E0090
    rep #$30
    .a16
    .i16
    lda #.LOWORD(@handler)
    sta a:V_BRK_VEC
    brk
    .byte $EA         ; BRK signature byte
    sep #$20
    .a8
    lda f:$7E0090
    cmp #$A5
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; native BRK did not reach the installed handler
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A6.02 — COP has its own vector
; provenance: Documented (WDC datasheet; SNESdev Wiki vectors)
.proc test_a6_02
    .a16
    .i16
    jmp @start
@handler:
    sep #$20
    .a8
    lda #$C0
    sta f:$7E0091
    rep #$30
    .a16
    .i16
    rti
@start:
    rep #$30
    .a16
    .i16
    sep #$20
    .a8
    lda #$00
    sta f:$7E0091
    rep #$30
    .a16
    .i16
    lda #.LOWORD(@handler)
    sta a:V_COP_VEC
    ; Encoded as raw bytes rather than `cop #$00`. Immediate addressing on COP is accepted by
    ; recent ca65 git builds but rejected as an illegal addressing mode by the 2.19 release
    ; that CI installs from apt, and the ROM must assemble identically on both.
    .byte $02, $00    ; cop #$00
    sep #$20
    .a8
    lda f:$7E0091
    cmp #$C0
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; COP did not reach its own vector
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A6.03 — D cleared on interrupt
; provenance: Documented (WDC datasheet)
.proc test_a6_03
    .a16
    .i16
    jmp @start
@handler:
    sep #$20
    .a8
    php
    pla
    and #$08          ; D flag
    sta f:$7E0092
    rep #$30
    .a16
    .i16
    rti
@start:
    rep #$30
    .a16
    .i16
    lda #.LOWORD(@handler)
    sta a:V_BRK_VEC
    sep #$20
    .a8
    lda #$FF
    sta f:$7E0092     ; poison, so 'handler never ran' cannot look like a pass
    sed
    brk
    .byte $EA
    cld
    sep #$20
    .a8
    lda f:$7E0092
    cmp #$00
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; D was not cleared on interrupt entry
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A6.04 — I set on interrupt
; provenance: Documented (WDC datasheet)
.proc test_a6_04
    .a16
    .i16
    jmp @start
@handler:
    sep #$20
    .a8
    php
    pla
    and #$04          ; I flag
    sta f:$7E0093
    rep #$30
    .a16
    .i16
    rti
@start:
    rep #$30
    .a16
    .i16
    lda #.LOWORD(@handler)
    sta a:V_BRK_VEC
    sep #$20
    .a8
    lda #$00
    sta f:$7E0093
    cli
    brk
    .byte $EA
    sep #$20
    .a8
    lda f:$7E0093
    cmp #$04
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; I was not set on interrupt entry
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A6.05 — Native pushes 4 bytes
; provenance: Documented (WDC datasheet)
.proc test_a6_05
    .a16
    .i16
    jmp @start
@handler:
    rep #$30
    .a16
    .i16
    tsc
    sta f:$7E0094     ; stack pointer as seen inside the handler
    rti
@start:
    rep #$30
    .a16
    .i16
    lda #.LOWORD(@handler)
    sta a:V_BRK_VEC
    tsc
    sta f:$7E0096     ; stack pointer before the interrupt
    brk
    .byte $EA
    rep #$30
    .a16
    .i16
    lda f:$7E0096
    sec
    sbc f:$7E0094
    cmp #$0004
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; native interrupt did not push exactly 4 bytes
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A6.06 — Emulation pushes 3 bytes
; provenance: Documented (WDC datasheet)
.proc test_a6_06
    .a16
    .i16
    jmp @start
@handler:
    tsx               ; X = S low byte (8-bit index in emulation)
    txa
    sta f:$7E0098
    rti
@start:
    rep #$30
    .a16
    .i16
    lda #.LOWORD(@handler)
    sta a:V_BRK_VEC
    ; Poison both slots so a handler that never runs cannot look like a pass.
    sep #$20
    .a8
    lda #$EE
    sta f:$7E0098
    lda #$EE
    sta f:$7E0099
    sec
    xce               ; -> emulation
    .a8
    .i8
    tsx
    txa
    sta f:$7E0099     ; S low byte before the interrupt
    brk
    .byte $EA
    clc
    xce               ; -> native (m/x stay 1: still 8-bit)
    .a8
    .i8
    sep #$20
    .a8
    lda f:$7E0099
    sec
    sbc f:$7E0098
    cmp #$03
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; emulation interrupt did not push exactly 3 bytes
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A6.07 — BRK skips signature byte
; provenance: Documented (WDC datasheet)
.proc test_a6_07
    .a16
    .i16
    jmp @start
@handler:
    rti
@start:
    rep #$30
    .a16
    .i16
    lda #.LOWORD(@handler)
    sta a:V_BRK_VEC
    clc               ; RTI restores P, so carry comes back CLEAR...
    brk
    .byte $38         ; ...unless PC returned here, where $38 is SEC
    php
    sep #$20
    .a8
    pla
    and #$01          ; carry
    cmp #$00
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; BRK pushed PC+1, so the signature byte executed
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A6.08 — WDM is a 2-byte NOP
; provenance: Documented (WDC datasheet)
.proc test_a6_08
    .a16
    .i16
    ; WDM consumes its operand byte. If it did not, the $38 below would run as SEC.
    rep #$30
    .a16
    .i16
    lda #$1234
    clc
    .byte $42, $38    ; WDM #$38  (the operand is SEC if wrongly executed)
    sta f:$7E00A0     ; stash A before the carry check clobbers it
    php
    sep #$20
    .a8
    pla
    and #$01          ; carry
    cmp #$00
    beq :+
    jmp @fail1
  :
    rep #$30
    .a16
    .i16
    lda f:$7E00A0
    cmp #$1234
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; WDM did not consume its operand byte
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; WDM disturbed the accumulator
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; A7.01 — 8-bit BCD ADC
; provenance: Documented (WDC datasheet)
.proc test_a7_01
    .a16
    .i16
    ; SED; CLC; LDA #$09; ADC #$01 -> A=$10, C=0.
    rep #$30
    .a16
    .i16
    sep #$20
    .a8
    sed
    clc
    lda #$09
    adc #$01
    cld
    cmp #$10
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; 8-bit BCD ADC produced the wrong result
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A7.02 — 16-bit BCD ADC
; provenance: Documented (WDC datasheet)
.proc test_a7_02
    .a16
    .i16
    ; m=0; SED; CLC; LDA #$0999; ADC #$0001 -> A=$1000.
    rep #$30
    .a16
    .i16
    sed
    clc
    lda #$0999
    adc #$0001
    cld
    cmp #$1000
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; 16-bit BCD ADC produced the wrong result
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A7.03 — 8-bit BCD SBC
; provenance: Documented (WDC datasheet)
.proc test_a7_03
    .a16
    .i16
    ; SED; SEC; LDA #$10; SBC #$01 -> A=$09.
    rep #$30
    .a16
    .i16
    sep #$20
    .a8
    sed
    sec
    lda #$10
    sbc #$01
    cld
    cmp #$09
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; 8-bit BCD SBC produced the wrong result
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A7.04 — Decimal V (golden)
; provenance: Contested (V in decimal mode is undefined; ares/bsnes/Mesen2 share a convention, which is agreement, not authority)
.proc test_a7_04
    .a16
    .i16
    ; SED; CLC; LDA #$99; ADC #$01 -> A=$00 with carry out. The A result is documented and
    ; is checked; V is NOT — it is captured and reported as a variant instead.
    rep #$30
    .a16
    .i16
    sep #$20
    .a8
    sed
    clc
    lda #$99
    adc #$01
    cld
    php
    pla               ; stash P before the compare clobbers it
    sta f:$7E0060
    txa
    ; Re-run to get A back for the documented half of the check.
    sed
    clc
    lda #$99
    adc #$01
    cld
    cmp #$00
    beq :+
    jmp @fail1
  :
    ; Now branch on the observed V bit (P bit 6) and report it as a variant.
    lda f:$7E0060
    and #$40
    beq :+
    lda #$03          ; variant 1 = V observed SET   ((1<<1)|1)
    sta f:$7EE010
    jmp test_restore
    :
    lda #$05          ; variant 2 = V observed CLEAR ((2<<1)|1)
    sta f:$7EE010
    jmp test_restore
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; decimal ADC $99+$01 did not produce $00
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A8.01 — MVN fwd, A=$FFFF
; provenance: Documented (WDC datasheet)
.proc test_a8_01
    .a16
    .i16
    ; Copy 4 bytes within bank $7E using MVN; A must end at $FFFF.
    rep #$30
    .a16
    .i16
    sep #$20
    .a8
    lda #$11
    sta f:$7E2000
    lda #$22
    sta f:$7E2001
    lda #$33
    sta f:$7E2002
    lda #$44
    sta f:$7E2003
    rep #$30
    .a16
    .i16
    ldx #$2000
    ldy #$2100
    lda #$0003        ; count-1
    mvn #$7E,#$7E    ; literal bank numbers; `mvn $7E,$7E` would mean bank $00
    phk
    plb               ; MVN left DBR = destination bank; restore for later reads
    cmp #$FFFF
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda f:$7E2100
    cmp #$11
    beq :+
    jmp @fail2
  :
    lda f:$7E2103
    cmp #$44
    beq :+
    jmp @fail3
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; MVN did not leave A = $FFFF
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; MVN did not copy the first byte
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
@fail3:
    ; MVN did not copy the last byte
    sep #$20
    .a8
    lda #$06
    sta f:$7EE010
    jmp test_restore
.endproc

; A8.02 — MVN sets DBR=dest
; provenance: Documented (SNESdev Errata, 65C816 section)
.proc test_a8_02
    .a16
    .i16
    ; After MVN $7E,$7E the data bank register is the destination bank ($7E), not $00.
    rep #$30
    .a16
    .i16
    ldx #$2000
    ldy #$2100
    lda #$0000        ; one byte
    mvn #$7E,#$7E    ; literal bank numbers; `mvn $7E,$7E` would mean bank $00
    phb
    sep #$20
    .a8
    pla
    cmp #$7E
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; MVN did not leave DBR = destination bank
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; A8.03 — MVP copies backward
; provenance: Documented (WDC datasheet)
.proc test_a8_03
    .a16
    .i16
    ; MVP walks X and Y downward; point them at the LAST byte of each block.
    rep #$30
    .a16
    .i16
    sep #$20
    .a8
    lda #$AA
    sta f:$7E2200
    lda #$BB
    sta f:$7E2201
    rep #$30
    .a16
    .i16
    ldx #$2201
    ldy #$2301
    lda #$0001        ; two bytes
    mvp #$7E,#$7E    ; literal bank numbers; `mvp $7E,$7E` would mean bank $00
    phk
    plb
    sep #$20
    .a8
    lda f:$7E2300
    cmp #$AA
    beq :+
    jmp @fail1
  :
    lda f:$7E2301
    cmp #$BB
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; MVP did not copy the low byte
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; MVP did not copy the high byte
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; A9.01 — BIT imm vs abs
; provenance: Documented (WDC datasheet)
.proc test_a9_01
    .a16
    .i16
    ; BIT #imm must leave N and V untouched; BIT dp must set them from the operand.
    ; BIT has no long-addressing mode, so the operand is staged in the direct page
    ; (DP = $0000, so dp $50 is $00:0050, the low-WRAM mirror of $7E:0050).
    rep #$30
    .a16
    .i16
    sep #$20
    .a8
    lda #$C0
    sta f:$7E0050
    ; Clear N and V, then BIT #$00 — Z should set, N/V must stay clear.
    clv
    lda #$01
    bit #$00
    php
    pla
    and #$C0          ; N and V
    cmp #$00
    beq :+
    jmp @fail1
  :
    ; Now BIT dp against $C0 — both N and V must set.
    lda #$FF
    bit $50
    php
    pla
    and #$C0
    cmp #$C0
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; BIT #imm wrongly modified N or V
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; BIT dp did not set N and V from memory bits 7/6
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; A9.02 — XBA swaps A halves
; provenance: Documented (WDC datasheet)
.proc test_a9_02
    .a16
    .i16
    ; XBA is always a 16-bit operation on C, regardless of the m flag.
    rep #$30
    .a16
    .i16
    lda #$1234
    xba
    cmp #$3412
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; XBA did not swap the accumulator halves
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; C1.01 — OAM word write/read
; provenance: Documented (SNESdev Wiki, OAM; fullsnes)
.proc test_c1_01
    .a16
    .i16
    ; OAMADDR is a WORD address. Two byte writes to $2104 fill one word, low byte first.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    stz $2102         ; OAMADDR = word 0
    stz $2103
    lda #$AA
    sta $2104
    lda #$BB
    sta $2104         ; word 0 now committed
    stz $2102         ; rewind to word 0 to read it back
    stz $2103
    lda $2138
    cmp #$AA
    beq :+
    jmp @fail1
  :
    lda $2138
    cmp #$BB
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; OAM low byte did not read back
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; OAM high byte did not read back
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; C1.02 — OAM odd write latched
; provenance: Documented (SNESdev Wiki, OAM; anomie)
.proc test_c1_02
    .a16
    .i16
    ; Seed word 1 with a known value, then write THREE bytes from word 0. The third byte is
    ; latched as the low half of word 1 and must not be committed on its own.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    ; --- seed word 1 = $EEDD ---
    lda #$01
    sta $2102         ; OAMADDR = word 1
    stz $2103
    lda #$DD
    sta $2104
    lda #$EE
    sta $2104
    ; --- three bytes starting at word 0 ---
    stz $2102
    stz $2103
    lda #$11
    sta $2104
    lda #$22
    sta $2104         ; word 0 committed
    lda #$33
    sta $2104         ; latched only — must NOT reach word 1
    ; --- read back ---
    stz $2102
    stz $2103
    lda $2138
    cmp #$11
    beq :+
    jmp @fail1
  :
    lda $2138
    cmp #$22
    beq :+
    jmp @fail2
  :
    lda $2138
    cmp #$DD
    beq :+
    jmp @fail3
  :
    lda $2138
    cmp #$EE
    beq :+
    jmp @fail4
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; word 0 low byte wrong
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; word 0 high byte wrong
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
@fail3:
    ; the odd trailing byte was committed (it must stay in the latch)
    sep #$20
    .a8
    lda #$06
    sta f:$7EE010
    jmp test_restore
@fail4:
    ; word 1 high byte was disturbed
    sep #$20
    .a8
    lda #$08
    sta f:$7EE010
    jmp test_restore
.endproc

; C1.03 — OAMADDR reload clears
; provenance: Documented (SNESdev Wiki, OAM; anomie)
.proc test_c1_03
    .a16
    .i16
    ; Write an odd byte count, then reload OAMADDR: the pending latch is discarded and the
    ; next pair starts cleanly rather than being offset by one byte.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda #$02
    sta $2102         ; word 2
    stz $2103
    lda #$99
    sta $2104         ; leave a byte pending in the latch
    lda #$02
    sta $2102         ; reload -> discard the pending byte
    stz $2103
    lda #$44
    sta $2104
    lda #$55
    sta $2104
    lda #$02
    sta $2102
    stz $2103
    lda $2138
    cmp #$44
    beq :+
    jmp @fail1
  :
    lda $2138
    cmp #$55
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; reloading OAMADDR did not discard the pending latch byte
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; word high byte wrong after OAMADDR reload
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; C1.04 — OAM rd/wr one counter
; provenance: Documented (SNESdev Wiki, OAM)
.proc test_c1_04
    .a16
    .i16
    ; Write one word, then read one byte, then read again: the read pointer must have followed
    ; the write pointer rather than tracking separately.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda #$04
    sta $2102
    stz $2103
    lda #$5A
    sta $2104
    lda #$A5
    sta $2104
    lda #$7E
    sta $2104
    lda #$E7
    sta $2104         ; words 4 and 5 written
    lda #$05
    sta $2102         ; point at word 5 only
    stz $2103
    lda $2138
    cmp #$7E
    beq :+
    jmp @fail1
  :
    lda $2138
    cmp #$E7
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; shared counter: word 5 low byte wrong
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; shared counter: word 5 high byte wrong
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; C1.05 — OAM high table mirror
; provenance: Documented (SNESdev Wiki, OAM; fullsnes)
.proc test_c1_05
    .a16
    .i16
    ; Write through the mirror at word $110 and read back at the real address, word $100.
    ; The high table commits per byte, so no write-twice pairing is involved.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda #$10
    sta $2102
    lda #$01          ; OAMADDR = word $110 (byte $220), bit 7 clear
    sta $2103
    lda #$5C
    sta $2104
    lda #$C5
    sta $2104
    ; --- read the real high-table bytes ---
    lda #$00
    sta $2102
    lda #$01          ; OAMADDR = word $100 (byte $200)
    sta $2103
    lda $2138
    cmp #$5C
    beq :+
    jmp @fail1
  :
    lda $2138
    cmp #$C5
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; OAM high table did not mirror: byte $220 -> $200
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; OAM high table did not mirror: byte $221 -> $201
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; C2.01 — VMAIN step 1 word
; provenance: Documented (SNESdev Wiki, PPU registers; fullsnes)
.proc test_c2_01
    .a16
    .i16
    ; VMAIN=$80: step 1 word, increment after the HIGH byte. Three words written back to back
    ; must land at consecutive addresses.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda #$80
    sta $2115
    rep #$30
    .a16
    .i16
    ldx #$1000
    stx $2116
    lda #$1111
    sta $2118
    lda #$2222
    sta $2118
    lda #$3333
    sta $2118
    ; Read back word $1001. The first read after setting the address is the stale prefetch,
    ; so discard it and take the second (see C2.03).
    ldx #$1001
    stx $2116
    lda $2139         ; prefetch, discarded
    ldx #$1001
    stx $2116
    sep #$20
    .a8
    lda $2139
    cmp #$22
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; step-1 increment did not reach word $1001
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; C2.02 — VMAIN low-byte trigger
; provenance: Documented (SNESdev Wiki, PPU registers; fullsnes)
.proc test_c2_02
    .a16
    .i16
    ; VMAIN=$00 increments after $2118 (the LOW byte), so writing only low bytes fills the low
    ; half of consecutive words and never touches the high halves. This is exactly how the
    ; runtime uploads its 1bpp font, so it is load-bearing here.
    rep #$30
    .a16
    .i16
    phk
    plb
    ; Clear two words first so the high bytes are known.
    sep #$20
    .a8
    lda #$80
    sta $2115
    rep #$30
    .a16
    .i16
    ldx #$1100
    stx $2116
    lda #$0000
    sta $2118
    sta $2118
    ; Now low-byte-only writes.
    sep #$20
    .a8
    stz $2115         ; VMAIN = $00: increment after the LOW byte
    rep #$30
    .a16
    .i16
    ldx #$1100
    stx $2116
    sep #$20
    .a8
    lda #$3C
    sta $2118
    lda #$C3
    sta $2118
    ; Read back word $1100: low $3C, high still 0.
    rep #$30
    .a16
    .i16
    ldx #$1100
    stx $2116
    lda $2139
    ldx #$1100
    stx $2116
    lda $2139
    cmp #$003C
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; low-byte-only write disturbed the high byte, or did not increment
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; C2.03 — VRAM read prefetch
; provenance: Documented (SNESdev Wiki; docs/ppu.md edge case 4)
.proc test_c2_03
    .a16
    .i16
    ; Write two distinguishable words, then set the address and read TWICE. The first read is
    ; the prefetch latched when the address was written; the second is the real value.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda #$80
    sta $2115
    rep #$30
    .a16
    .i16
    ldx #$1200
    stx $2116
    lda #$ABCD
    sta $2118
    lda #$1234
    sta $2118         ; word $1200 = $ABCD, word $1201 = $1234
    ldx #$1200
    stx $2116
    lda $2139         ; prefetch of word $1200
    and #$FFFF
    cmp #$ABCD
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; the read after setting VMADD did not return word $1200
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; C2.04 — VRAM bit 15 unconnected
; provenance: Documented (SNESdev Wiki, PPU registers; fullsnes)
.proc test_c2_04
    .a16
    .i16
    ; VRAM is 32K words, so a 16-bit word address has one bit too many. Bit 15 is unconnected,
    ; making $8xxx an alias of $0xxx rather than an out-of-range access.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda #$80
    sta $2115
    rep #$30
    .a16
    .i16
    ldx #$1300
    stx $2116
    lda #$BEEF
    sta $2118
    ; Read the same word through the mirrored address.
    ldx #$9300
    stx $2116
    lda $2139
    ldx #$9300
    stx $2116
    lda $2139
    cmp #$BEEF
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; VRAM address bit 15 was decoded (it must be unconnected)
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; C2.05 — VMAIN step 32 words
; provenance: Documented (SNESdev Wiki, PPU registers; fullsnes)
.proc test_c2_05
    .a16
    .i16
    ; Write with step=32, then read the far word back to confirm the stride.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda #$81          ; VMAIN: step 32 words, increment after the high byte
    sta $2115
    rep #$30
    .a16
    .i16
    ldx #$1400
    stx $2116
    lda #$0F0F
    sta $2118
    lda #$F0F0
    sta $2118         ; words $1400 and $1420
    ; Read word $1420 with the plain step so the address does not run away.
    sep #$20
    .a8
    lda #$80
    sta $2115
    rep #$30
    .a16
    .i16
    ldx #$1420
    stx $2116
    lda $2139
    ldx #$1420
    stx $2116
    lda $2139
    cmp #$F0F0
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; VMAIN step-32 increment did not land at word $1420
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; C2.06 — VMAIN remap hits bus
; provenance: Documented (SNESdev Wiki, PPU registers; fullsnes; anomie)
.proc test_c2_06
    .a16
    .i16
    ; Two back-to-back writes with remap 01 active, then read both target words with remap off.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda #$84          ; VMAIN: remap 01 (8-bit), step 1, increment after the high byte
    sta $2115
    rep #$30
    .a16
    .i16
    ldx #$1503
    stx $2116
    lda #$CAFE
    sta $2118         ; register $1503 -> bus word $1518
    lda #$B0BA
    sta $2118         ; register $1504 -> bus word $1520
    ; --- read both back with translation off ---
    sep #$20
    .a8
    lda #$80
    sta $2115
    rep #$30
    .a16
    .i16
    ldx #$1518
    stx $2116
    lda $2139
    cmp #$CAFE
    beq :+
    jmp @fail1
  :
    ldx #$1520
    stx $2116
    lda $2139
    cmp #$B0BA
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; remap 01 did not translate register $1503 to bus word $1518
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; the remap fed back into the address register (the second write missed word $1520)
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; C3.01 — CGRAM two-write commit
; provenance: Documented (SNESdev Wiki, PPU registers; fullsnes)
.proc test_c3_01
    .a16
    .i16
    ; $2122 is written twice per colour: low byte then high. Read back through $213B.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda #$10
    sta $2121         ; CGADD = colour 16
    lda #$34
    sta $2122
    lda #$12
    sta $2122         ; colour 16 = $1234
    lda #$10
    sta $2121
    lda $213B
    cmp #$34
    beq :+
    jmp @fail1
  :
    lda $213B
    and #$7F          ; bit 7 of the second read is PPU2 open bus
    cmp #$12
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; CGRAM low byte did not read back
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; CGRAM high byte did not read back
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; C3.02 — CGADD resets flipflop
; provenance: Documented (SNESdev Wiki, PPU registers)
.proc test_c3_02
    .a16
    .i16
    ; Leave a byte pending, reload CGADD, then write a full colour: the pending byte must be
    ; discarded rather than pairing with the next write.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda #$11
    sta $2121
    lda #$99
    sta $2122         ; pending
    lda #$11
    sta $2121         ; reload -> flipflop reset
    lda #$78
    sta $2122
    lda #$56
    sta $2122
    lda #$11
    sta $2121
    lda $213B
    cmp #$78
    beq :+
    jmp @fail1
  :
    lda $213B
    and #$7F
    cmp #$56
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; CGADD write did not reset the flipflop
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; CGRAM high byte wrong after flipflop reset
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; C3.03 — OPHCT is a 9-bit pair
; provenance: Documented (SNESdev Wiki, PPU registers; fullsnes)
.proc test_c3_03
    .a16
    .i16
    ; $213F resets the read flipflops, $2137 latches, then two $213C reads give low byte and
    ; (in bit 0 only) bit 8. Reconstructed, that must be a real position on the scanline.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda $213F         ; reset the OPHCT/OPVCT read flipflops
    lda $2137         ; latch H and V
    lda $213C         ; low 8 bits
    xba
    lda $213C
    and #$01          ; bit 0 is counter bit 8; bits 1-7 are open bus
    xba
    rep #$20
    .a16
    and #$01FF
    cmp #$0000
    bcs :+
    jmp @fail1
  :
    cmp #$0155
    bcc :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; reconstructed H counter is outside a scanline
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; C3.04 — H counter advances
; provenance: Documented (SNESdev Wiki, PPU registers)
.proc test_c3_04
    .a16
    .i16
    ; Latch, burn a known amount of time, latch again. The elapsed dot count must be non-zero
    ; and must not have wrapped past the end of the line.
    rep #$30
    .a16
    .i16
    phk
    plb
    jsr hv_begin
    nop
    nop
    nop
    nop
    nop
    nop
    nop
    nop
    nop
    nop
    nop
    nop
    nop
    nop
    nop
    nop
    jsr hv_end
    rep #$30
    .a16
    .i16
    lda f:$7E0048     ; elapsed dots
    cmp #$0001
    bcs :+
    jmp @fail1
  :
    cmp #$0155
    bcc :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; the H counter did not advance plausibly across 16 NOPs
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; C3.05 — $213F resets flipflop
; provenance: Documented (SNESdev Wiki, PPU registers; fullsnes)
.proc test_c3_05
    .a16
    .i16
    ; Latch once, then read low / high / reset / low. Nothing re-latches in between, so the
    ; two low reads sample the same frozen value and any difference is a flipflop bug.
    rep #$30
    .a16
    .i16
    phk
    plb
    cld               ; the SBC below must not run in decimal mode
    sep #$20
    .a8
    lda $213F         ; reset both read flipflops
    lda $2137         ; latch H and V
    lda $213C         ; H low
    sta f:$7E0100
    lda $213C         ; H high — the flipflop is now set
    lda $213F         ; reset both flipflops again
    lda $213C         ; must be H low once more
    sec
    sbc f:$7E0100
    cmp #$00
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; $213F did not reset the OPHCT flipflop (the third read was not the low byte)
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; C13.01 — PPU1 open bus in $213E
; provenance: Documented (SNESdev Wiki, PPU registers; fullsnes)
.proc test_c13_01
    .a16
    .i16
    ; Drive PPU1 open bus to $10 via an OAM read, check $213E bit 4, then drive it to $00 and
    ; check again. Only bit 4 is examined: bits 7-6 are the sprite flags and 5-0 the version.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    ; --- open bus := $10 ---
    lda #$08
    sta $2102
    stz $2103
    lda #$10
    sta $2104
    lda #$00
    sta $2104
    lda #$08
    sta $2102
    stz $2103
    lda $2138         ; returns $10 and refreshes PPU1 open bus with it
    lda $213E
    and #$10
    cmp #$10
    beq :+
    jmp @fail1
  :
    ; --- open bus := $00 ---
    lda #$08
    sta $2102
    stz $2103
    lda #$00
    sta $2104
    lda #$00
    sta $2104
    lda #$08
    sta $2102
    stz $2103
    lda $2138         ; returns $00
    lda $213E
    and #$10
    cmp #$00
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; $213E bit 4 did not follow PPU1 open bus set to $10
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; $213E bit 4 did not follow PPU1 open bus cleared to $00
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; C13.02 — PPU2 open bus in $213F
; provenance: Documented (SNESdev Wiki, PPU registers; fullsnes)
.proc test_c13_02
    .a16
    .i16
    ; Same shape as C13.01 but on the other chip: CGRAM reads go through PPU2, so a $213B read
    ; is what refreshes this latch.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    ; --- open bus := $20 ---
    lda #$20
    sta $2121
    lda #$20
    sta $2122
    lda #$00
    sta $2122
    lda #$20
    sta $2121
    lda $213B         ; returns $20 and refreshes PPU2 open bus with it
    lda $213F
    and #$20
    cmp #$20
    beq :+
    jmp @fail1
  :
    ; --- open bus := $00 ---
    lda #$20
    sta $2121
    lda #$00
    sta $2122
    lda #$00
    sta $2122
    lda #$20
    sta $2121
    lda $213B         ; returns $00
    lda $213F
    and #$20
    cmp #$00
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; $213F bit 5 did not follow PPU2 open bus set to $20
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; $213F bit 5 did not follow PPU2 open bus cleared to $00
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; C13.03 — PPU1/PPU2 bus separate
; provenance: Corroborated (the bsnes/ares lineage and Mesen2 model two distinct latches)
.proc test_c13_03
    .a16
    .i16
    ; Drive the two latches to opposite values and read both back. Then swap and repeat, so a
    ; shared latch cannot pass by accident in one polarity.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    ; --- seed OAM byte $10 / $00 and CGRAM low byte $20 / $00 ---
    lda #$08
    sta $2102
    stz $2103
    lda #$10
    sta $2104
    lda #$00
    sta $2104         ; OAM word 8 = $0010
    ; Word 9 must be seeded too, not assumed zero: it is read below to drive PPU1 open bus to
    ; $00, and whatever the previous tests or the power-on fill left there would otherwise
    ; decide the result. Mesen2 and snes9x disagree on that leftover, which is not a hardware
    ; difference — it is this test failing to control its own inputs.
    lda #$00
    sta $2104
    lda #$00
    sta $2104         ; OAM word 9 = $0000
    lda #$20
    sta $2121
    lda #$20
    sta $2122
    lda #$00
    sta $2122         ; colour $20 = $0020
    lda #$00
    sta $2122
    lda #$00
    sta $2122         ; colour $21 = $0000, for the same reason as OAM word 9
    ; --- PPU1 := $10, PPU2 := $00 ---
    lda #$08
    sta $2102
    stz $2103
    lda $2138         ; PPU1 open bus := $10
    lda #$21
    sta $2121
    lda $213B         ; colour $21 low byte = $00; PPU2 open bus := $00
    lda $213E
    and #$10
    cmp #$10
    beq :+
    jmp @fail1
  :
    lda $213F
    and #$20
    cmp #$00
    beq :+
    jmp @fail2
  :
    ; --- PPU1 := $00, PPU2 := $20 ---
    lda #$09
    sta $2102
    stz $2103
    lda $2138         ; OAM word 9 is zero; PPU1 open bus := $00
    lda #$20
    sta $2121
    lda $213B         ; PPU2 open bus := $20
    lda $213E
    and #$10
    cmp #$00
    beq :+
    jmp @fail3
  :
    lda $213F
    and #$20
    cmp #$20
    beq :+
    jmp @fail4
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; refreshing PPU2 open bus clobbered PPU1's latch
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; PPU2 open bus read back as PPU1's value
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
@fail3:
    ; PPU1 open bus read back as PPU2's value
    sep #$20
    .a8
    lda #$06
    sta f:$7EE010
    jmp test_restore
@fail4:
    ; refreshing PPU1 open bus clobbered PPU2's latch
    sep #$20
    .a8
    lda #$08
    sta f:$7EE010
    jmp test_restore
.endproc

; C14.01 — PPU1 version (golden)
; provenance: Documented (SNESdev Wiki, PPU registers; fullsnes)
.proc test_c14_01
    .a16
    .i16
    ; Report the low nibble of $213E as the variant code.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda $213E
    and #$0F          ; PPU1 version
    asl a
    ora #$01          ; encode as (version << 1) | 1
    sta f:$7EE010
    jmp test_restore
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
.endproc

; C14.02 — PPU2 version (golden)
; provenance: Documented (SNESdev Wiki, PPU registers; fullsnes)
.proc test_c14_02
    .a16
    .i16
    ; Report the low nibble of $213F as the variant code.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda $213F
    and #$0F          ; PPU2 version
    asl a
    ora #$01
    sta f:$7EE010
    jmp test_restore
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
.endproc

; C11.06 — MPY is 16x8 signed
; provenance: Documented (SNESdev Wiki, Mode 7; fullsnes)
.proc test_c11_06
    .a16
    .i16
    ; Positive case: M7A = $0100 (256), M7B high byte = $02, so the product is 512 = $000200.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda #$00
    sta $211B         ; M7A low
    lda #$01
    sta $211B         ; M7A high -> M7A = $0100
    lda #$00
    sta $211C         ; M7B low (ignored by the multiply)
    lda #$02
    sta $211C         ; M7B high -> multiplicand = +2
    lda $2134
    cmp #$00
    beq :+
    jmp @fail1
  :
    lda $2135
    cmp #$02
    beq :+
    jmp @fail2
  :
    lda $2136
    cmp #$00
    beq :+
    jmp @fail3
  :
    ; The low byte of M7B must not participate: rewriting it alone cannot change the product.
    lda #$FF
    sta $211C         ; M7B low = $FF
    lda #$02
    sta $211C         ; M7B high still $02
    lda $2135
    cmp #$02
    beq :+
    jmp @fail4
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; MPYL wrong for 256 * 2
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; MPYM wrong for 256 * 2
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
@fail3:
    ; MPYH wrong for 256 * 2
    sep #$20
    .a8
    lda #$06
    sta f:$7EE010
    jmp test_restore
@fail4:
    ; the low byte of M7B leaked into the multiply
    sep #$20
    .a8
    lda #$08
    sta f:$7EE010
    jmp test_restore
.endproc

; C11.06b — MPY sign handling
; provenance: Documented (SNESdev Wiki, Mode 7; fullsnes)
.proc test_c11_06b
    .a16
    .i16
    ; Negative multiplicand: M7A = $0002, M7B high = $FF (-1) -> -2 = $FFFFFE.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda #$02
    sta $211B
    lda #$00
    sta $211B         ; M7A = $0002
    lda #$00
    sta $211C
    lda #$FF
    sta $211C         ; multiplicand = -1
    lda $2134
    cmp #$FE
    beq :+
    jmp @fail1
  :
    lda $2135
    cmp #$FF
    beq :+
    jmp @fail2
  :
    lda $2136
    cmp #$FF
    beq :+
    jmp @fail3
  :
    ; Negative multiplier: M7A = $FFFF (-1), M7B high = $02 -> -2 = $FFFFFE.
    lda #$FF
    sta $211B
    lda #$FF
    sta $211B         ; M7A = $FFFF
    lda #$00
    sta $211C
    lda #$02
    sta $211C
    lda $2134
    cmp #$FE
    beq :+
    jmp @fail4
  :
    lda $2136
    cmp #$FF
    beq :+
    jmp @fail5
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; MPYL wrong for 2 * -1 (M7B high must be signed)
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; MPYM wrong for 2 * -1
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
@fail3:
    ; the product did not sign-extend to 24 bits
    sep #$20
    .a8
    lda #$06
    sta f:$7EE010
    jmp test_restore
@fail4:
    ; MPYL wrong for -1 * 2 (M7A must be signed)
    sep #$20
    .a8
    lda #$08
    sta f:$7EE010
    jmp test_restore
@fail5:
    ; the product did not sign-extend for a negative M7A
    sep #$20
    .a8
    lda #$0A
    sta f:$7EE010
    jmp test_restore
.endproc

; C7.01 — Range Over at 32 sprites
; provenance: Documented (SNESdev Wiki, Sprites; fullsnes)
.proc test_c7_01
    .a16
    .i16
    rep #$30
    .a16
    .i16
    phk
    plb
    ; --- 2 sprites on the line: well under the limit, flag must stay clear ---
    sep #$20
    .a8
    lda #$00
    sta $2101         ; OBJSEL: size pair in bits 7-5, name base in bits 1-0
    ; --- low table: `on_line` sprites on one scanline, the rest parked off-screen ---
    stz $2102
    stz $2103
    rep #$10
    .i16
    ldx #$0000
@fill_a:
    lda #$00
    sta $2104         ; X = 0
    cpx #$0002
    bcs @off_a
    lda #100
    bra @sety_a
@off_a:
    lda #$F0          ; below the visible area in 224-line mode
@sety_a:
    sta $2104         ; Y
    lda #$00
    sta $2104         ; tile
    lda #$00
    sta $2104         ; attr
    inx
    cpx #$0080
    bne @fill_a
    ; --- high table: 32 bytes, 2 bits per sprite (bit 0 = X bit 8, bit 1 = size select) ---
    lda #$00
    sta $2102
    lda #$01
    sta $2103         ; OAMADDR = word $100, the high table
    ldx #$0000
@hi_a:
    lda #$00
    sta $2104
    inx
    cpx #$0020
    bne @hi_a
    ; --- render one complete frame, then sample and restore forced blank ---
    lda #$10
    sta $212C         ; OBJ on the main screen
    lda #$0F
    sta $2100         ; brightness 15, forced blank released
    jsr wait_vblank   ; land on a vblank boundary
    jsr wait_vblank   ; span one complete active period
    lda $213E
    pha
    lda #$8F
    sta $2100         ; forced blank again, as the rest of the battery expects
    stz $212C
    pla
    and #$40
    cmp #$00
    beq :+
    jmp @fail1
  :
    ; --- 40 sprites on the line: over the 32-sprite limit ---
    rep #$30
    .a16
    .i16
    sep #$20
    .a8
    lda #$00
    sta $2101         ; OBJSEL: size pair in bits 7-5, name base in bits 1-0
    ; --- low table: `on_line` sprites on one scanline, the rest parked off-screen ---
    stz $2102
    stz $2103
    rep #$10
    .i16
    ldx #$0000
@fill_b:
    lda #$00
    sta $2104         ; X = 0
    cpx #$0028
    bcs @off_b
    lda #100
    bra @sety_b
@off_b:
    lda #$F0          ; below the visible area in 224-line mode
@sety_b:
    sta $2104         ; Y
    lda #$00
    sta $2104         ; tile
    lda #$00
    sta $2104         ; attr
    inx
    cpx #$0080
    bne @fill_b
    ; --- high table: 32 bytes, 2 bits per sprite (bit 0 = X bit 8, bit 1 = size select) ---
    lda #$00
    sta $2102
    lda #$01
    sta $2103         ; OAMADDR = word $100, the high table
    ldx #$0000
@hi_b:
    lda #$00
    sta $2104
    inx
    cpx #$0020
    bne @hi_b
    ; --- render one complete frame, then sample and restore forced blank ---
    lda #$10
    sta $212C         ; OBJ on the main screen
    lda #$0F
    sta $2100         ; brightness 15, forced blank released
    jsr wait_vblank   ; land on a vblank boundary
    jsr wait_vblank   ; span one complete active period
    lda $213E
    pha
    lda #$8F
    sta $2100         ; forced blank again, as the rest of the battery expects
    stz $212C
    pla
    and #$40
    cmp #$40
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; Range Over set with only 2 sprites on the scanline
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; Range Over did not set with 40 sprites on one scanline
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; C7.02 — Time Over is slivers
; provenance: Documented (SNESdev Wiki, Sprites; fullsnes; anomie)
.proc test_c7_02
    .a16
    .i16
    ; OBJSEL size select lives in bits 7-5, not the low bits: mode 2 ($40) pairs 8x8 with
    ; 64x64, and the high table marks sprites 0-4 as the large member of that pair. Writing
    ; the mode number into the low bits instead sets the tile-name base and silently leaves
    ; the size pair at 8x8/16x16 — 10 slivers, comfortably inside the budget, no flag.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda #$40
    sta $2101         ; OBJSEL: size pair in bits 7-5, name base in bits 1-0
    ; --- low table: `on_line` sprites on one scanline, the rest parked off-screen ---
    stz $2102
    stz $2103
    rep #$10
    .i16
    ldx #$0000
@fill_a:
    lda #$00
    sta $2104         ; X = 0
    cpx #$0005
    bcs @off_a
    lda #100
    bra @sety_a
@off_a:
    lda #$F0          ; below the visible area in 224-line mode
@sety_a:
    sta $2104         ; Y
    lda #$00
    sta $2104         ; tile
    lda #$00
    sta $2104         ; attr
    inx
    cpx #$0080
    bne @fill_a
    ; --- high table: 32 bytes, 2 bits per sprite (bit 0 = X bit 8, bit 1 = size select) ---
    lda #$00
    sta $2102
    lda #$01
    sta $2103         ; OAMADDR = word $100, the high table
    ldx #$0000
@hi_a:
    lda #$00
    sta $2104
    inx
    cpx #$0020
    bne @hi_a
    ; Mark the leading sprites as the large size of the pair.
    lda #$00
    sta $2102
    lda #$01
    sta $2103
    lda #$AA
    sta $2104
    lda #$02
    sta $2104
    ; --- render one complete frame, then sample and restore forced blank ---
    lda #$10
    sta $212C         ; OBJ on the main screen
    lda #$0F
    sta $2100         ; brightness 15, forced blank released
    jsr wait_vblank   ; land on a vblank boundary
    jsr wait_vblank   ; span one complete active period
    lda $213E
    pha
    lda #$8F
    sta $2100         ; forced blank again, as the rest of the battery expects
    stz $212C
    pla
    pha
    and #$80
    cmp #$80
    beq :+
    jmp @fail1
  :
    pla
    and #$40
    cmp #$00
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; Time Over did not set for 40 slivers from 5 sprites
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; Range Over set for only 5 sprites (it is a sprite count, not a sliver count)
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; C7.08 — Flags ignore $212C
; provenance: Documented (SNESdev Wiki, Sprites; fullsnes)
.proc test_c7_08
    .a16
    .i16
    ; Same 40-sprite overflow as C7.01, but with OBJ left off the main screen entirely.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda #$00
    sta $2101         ; OBJSEL: size pair in bits 7-5, name base in bits 1-0
    ; --- low table: `on_line` sprites on one scanline, the rest parked off-screen ---
    stz $2102
    stz $2103
    rep #$10
    .i16
    ldx #$0000
@fill_a:
    lda #$00
    sta $2104         ; X = 0
    cpx #$0028
    bcs @off_a
    lda #100
    bra @sety_a
@off_a:
    lda #$F0          ; below the visible area in 224-line mode
@sety_a:
    sta $2104         ; Y
    lda #$00
    sta $2104         ; tile
    lda #$00
    sta $2104         ; attr
    inx
    cpx #$0080
    bne @fill_a
    ; --- high table: 32 bytes, 2 bits per sprite (bit 0 = X bit 8, bit 1 = size select) ---
    lda #$00
    sta $2102
    lda #$01
    sta $2103         ; OAMADDR = word $100, the high table
    ldx #$0000
@hi_a:
    lda #$00
    sta $2104
    inx
    cpx #$0020
    bne @hi_a
    ; --- render one complete frame, then sample and restore forced blank ---
    stz $212C         ; deliberately leave OBJ OFF the main screen
    lda #$0F
    sta $2100         ; brightness 15, forced blank released
    jsr wait_vblank   ; land on a vblank boundary
    jsr wait_vblank   ; span one complete active period
    lda $213E
    pha
    lda #$8F
    sta $2100         ; forced blank again, as the rest of the battery expects
    stz $212C
    pla
    and #$40
    cmp #$40
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; Range Over did not set while OBJ was off the main screen ($212C gates compositing, not evaluation)
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; C2.11 — VRAM locked in render
; provenance: Documented (SNESdev Wiki, PPU registers; fullsnes)
.proc test_c2_11
    .a16
    .i16
    ; Clear three words under forced blank, then try to write two of them from active display.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda #$80
    sta $2115         ; VMAIN step 1, increment after the high byte
    rep #$30
    .a16
    .i16
    ldx #$1600
    stx $2116
    lda #$0000
    sta $2118
    sta $2118
    sta $2118         ; words $1600-$1602 cleared
    ldx #$1600
    stx $2116         ; aim at $1600 before the window closes
    sep #$20
    .a8
    lda #$0F
    sta $2100         ; forced blank off — the access window now depends on position
    jsr wait_vblank
    jsr wait_vblank   ; a full settled frame
@wa_c211:
    lda $4212
    and #$80
    bne @wa_c211   ; wait for vblank to end
    rep #$10
    .i16
    ldx #$0400
@burn_c211:
    dex
    bne @burn_c211 ; ~20 scanlines in, well clear of the pre-render line
    rep #$20
    .a16
    lda #$AAAA
    sta $2118         ; must be dropped
    sta $2118         ; must be dropped
    sep #$20
    .a8
    lda #$8F
    sta $2100         ; forced blank restored
    ; --- read back: both words must still be zero ---
    rep #$30
    .a16
    .i16
    ldx #$1600
    stx $2116
    lda $2139
    cmp #$0000
    beq :+
    jmp @fail1
  :
    ldx #$1601
    stx $2116
    lda $2139
    cmp #$0000
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; a VRAM write during active display was not dropped
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; the second VRAM write during active display was not dropped
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; C2.10 — Dropped write still incs
; provenance: Documented (SNESdev Wiki, PPU registers; fullsnes; anomie)
.proc test_c2_10
    .a16
    .i16
    ; Same shape as C2.11, but the payload is the write that follows: if the two dropped writes
    ; advanced the address, the legal third write lands at $1602 rather than back at $1600.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    lda #$80
    sta $2115
    rep #$30
    .a16
    .i16
    ldx #$1610
    stx $2116
    lda #$0000
    sta $2118
    sta $2118
    sta $2118         ; words $1610-$1612 cleared
    ldx #$1610
    stx $2116
    sep #$20
    .a8
    lda #$0F
    sta $2100         ; forced blank off — the access window now depends on position
    jsr wait_vblank
    jsr wait_vblank   ; a full settled frame
@wa_c210:
    lda $4212
    and #$80
    bne @wa_c210   ; wait for vblank to end
    rep #$10
    .i16
    ldx #$0400
@burn_c210:
    dex
    bne @burn_c210 ; ~20 scanlines in, well clear of the pre-render line
    rep #$20
    .a16
    lda #$AAAA
    sta $2118         ; dropped, but the address must advance to $1611
    sta $2118         ; dropped, but the address must advance to $1612
    sep #$20
    .a8
    lda #$8F
    sta $2100         ; forced blank: the window is open again
    rep #$20
    .a16
    lda #$BBBB
    sta $2118         ; this one must land, and at $1612
    ; --- read back ---
    rep #$30
    .a16
    .i16
    ldx #$1612
    stx $2116
    lda $2139
    cmp #$BBBB
    beq :+
    jmp @fail1
  :
    ldx #$1610
    stx $2116
    lda $2139
    cmp #$0000
    beq :+
    jmp @fail2
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; the address did not advance across the dropped writes
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; the legal write landed at $1610 instead of $1612
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

; C1.06 — OAM addr reloads
; provenance: Documented (SNESdev Wiki, OAM; anomie)
.proc test_c1_06
    .a16
    .i16
    ; Seed three words, set the base to word 0, then walk the internal address forward to word
    ; 2. After a rendered frame the next read must come from word 0 again.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    stz $2102
    stz $2103
    lda #$11
    sta $2104
    lda #$22
    sta $2104         ; word 0
    lda #$33
    sta $2104
    lda #$44
    sta $2104         ; word 1
    lda #$55
    sta $2104
    lda #$66
    sta $2104         ; word 2
    ; --- base = word 0, then advance the internal counter to word 2 by reading ---
    stz $2102
    stz $2103
    lda $2138
    lda $2138
    lda $2138
    lda $2138         ; internal address now word 2
    ; --- render one complete frame; the reload happens as vblank begins ---
    lda #$0F
    sta $2100
    jsr wait_vblank
    jsr wait_vblank
    lda $2138         ; read while forced blank is still off
    sta f:$7E0102
    lda #$8F
    sta $2100
    lda f:$7E0102
    cmp #$11
    beq :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; the OAM address did not reload from its base across a frame
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
.endproc

; C9.04 — Overscan moves vblank
; provenance: Documented (SNESdev Wiki, Timing; fullsnes)
.proc test_c9_04
    .a16
    .i16
    ; Sample the V counter at the instant vblank begins, with overscan off and then on. Both
    ; samples take two wait_vblank calls so the setting has been stable for a whole frame —
    ; toggling $2133 mid-frame is its own documented hazard and is not what this measures.
    rep #$30
    .a16
    .i16
    phk
    plb
    sep #$20
    .a8
    stz $2133         ; overscan off: 224 visible lines
    jsr wait_vblank
    jsr wait_vblank
    lda $213F         ; reset the counter read flipflops
    lda $2137         ; latch H and V
    lda $213D         ; V low
    xba
    lda $213D
    and #$01          ; bit 0 is V bit 8; bits 1-7 are PPU2 open bus
    xba
    rep #$20
    .a16
    and #$01FF
    cmp #$00E1
    bcs :+
    jmp @fail1
  :
    cmp #$00E9
    bcc :+
    jmp @fail1
  :
    sep #$20
    .a8
    lda #$04
    sta $2133         ; overscan on: 239 visible lines
    jsr wait_vblank
    jsr wait_vblank
    lda $213F
    lda $2137
    lda $213D
    xba
    lda $213D
    and #$01
    xba
    rep #$20
    .a16
    and #$01FF
    cmp #$00F0
    bcs :+
    jmp @fail2
  :
    cmp #$00F8
    bcc :+
    jmp @fail2
  :
    sep #$20
    .a8
    stz $2133         ; restore
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jmp test_restore
@fail1:
    ; vblank did not begin near line 225 without overscan
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jmp test_restore
@fail2:
    ; overscan did not move the start of vblank to line 240
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jmp test_restore
.endproc

.segment "CATALOG"
.export _test_count
.export _test_entries
.export _test_names
.export _test_flags

_test_count:
    .word 73

; Entry points (16-bit; all tests live in bank $00).
_test_entries:
    .addr test_a1_01
    .addr test_a1_02
    .addr test_a1_03
    .addr test_a1_04
    .addr test_a1_05
    .addr test_a2_01
    .addr test_a2_02
    .addr test_a2_03
    .addr test_a2_04
    .addr test_a2_05
    .addr test_a3_01
    .addr test_a3_02
    .addr test_a3_03
    .addr test_a3_04
    .addr test_a3_05
    .addr test_a4_01
    .addr test_a4_02
    .addr test_a4_03
    .addr test_a4_04
    .addr test_a4_05
    .addr test_a5_01
    .addr test_a5_02
    .addr test_a5_03
    .addr test_a5_04
    .addr test_a5_05
    .addr test_a5_06
    .addr test_a6_01
    .addr test_a6_02
    .addr test_a6_03
    .addr test_a6_04
    .addr test_a6_05
    .addr test_a6_06
    .addr test_a6_07
    .addr test_a6_08
    .addr test_a7_01
    .addr test_a7_02
    .addr test_a7_03
    .addr test_a7_04
    .addr test_a8_01
    .addr test_a8_02
    .addr test_a8_03
    .addr test_a9_01
    .addr test_a9_02
    .addr test_c1_01
    .addr test_c1_02
    .addr test_c1_03
    .addr test_c1_04
    .addr test_c1_05
    .addr test_c2_01
    .addr test_c2_02
    .addr test_c2_03
    .addr test_c2_04
    .addr test_c2_05
    .addr test_c2_06
    .addr test_c3_01
    .addr test_c3_02
    .addr test_c3_03
    .addr test_c3_04
    .addr test_c3_05
    .addr test_c13_01
    .addr test_c13_02
    .addr test_c13_03
    .addr test_c14_01
    .addr test_c14_02
    .addr test_c11_06
    .addr test_c11_06b
    .addr test_c7_01
    .addr test_c7_02
    .addr test_c7_08
    .addr test_c2_11
    .addr test_c2_10
    .addr test_c1_06
    .addr test_c9_04

; Per-test flags: bit0 = scores toward the pass rate, bit1 = golden-vector.
_test_flags:
    .byte $01   ; A1.01
    .byte $01   ; A1.02
    .byte $01   ; A1.03
    .byte $01   ; A1.04
    .byte $01   ; A1.05
    .byte $01   ; A2.01
    .byte $01   ; A2.02
    .byte $01   ; A2.03
    .byte $01   ; A2.04
    .byte $01   ; A2.05
    .byte $01   ; A3.01
    .byte $01   ; A3.02
    .byte $01   ; A3.03
    .byte $01   ; A3.04
    .byte $01   ; A3.05
    .byte $01   ; A4.01
    .byte $01   ; A4.02
    .byte $01   ; A4.03
    .byte $01   ; A4.04
    .byte $01   ; A4.05
    .byte $01   ; A5.01
    .byte $01   ; A5.02
    .byte $01   ; A5.03
    .byte $01   ; A5.04
    .byte $01   ; A5.05
    .byte $01   ; A5.06
    .byte $01   ; A6.01
    .byte $01   ; A6.02
    .byte $01   ; A6.03
    .byte $01   ; A6.04
    .byte $01   ; A6.05
    .byte $01   ; A6.06
    .byte $01   ; A6.07
    .byte $01   ; A6.08
    .byte $01   ; A7.01
    .byte $01   ; A7.02
    .byte $01   ; A7.03
    .byte $02   ; A7.04
    .byte $01   ; A8.01
    .byte $01   ; A8.02
    .byte $01   ; A8.03
    .byte $01   ; A9.01
    .byte $01   ; A9.02
    .byte $01   ; C1.01
    .byte $01   ; C1.02
    .byte $01   ; C1.03
    .byte $01   ; C1.04
    .byte $01   ; C1.05
    .byte $01   ; C2.01
    .byte $01   ; C2.02
    .byte $01   ; C2.03
    .byte $01   ; C2.04
    .byte $01   ; C2.05
    .byte $01   ; C2.06
    .byte $01   ; C3.01
    .byte $01   ; C3.02
    .byte $01   ; C3.03
    .byte $01   ; C3.04
    .byte $01   ; C3.05
    .byte $01   ; C13.01
    .byte $01   ; C13.02
    .byte $01   ; C13.03
    .byte $02   ; C14.01
    .byte $02   ; C14.02
    .byte $01   ; C11.06
    .byte $01   ; C11.06b
    .byte $01   ; C7.01
    .byte $01   ; C7.02
    .byte $01   ; C7.08
    .byte $01   ; C2.11
    .byte $01   ; C2.10
    .byte $01   ; C1.06
    .byte $01   ; C9.04

; Menu labels, each a length-prefixed ASCII string.
_test_names:
    .addr @n_a1_01
    .addr @n_a1_02
    .addr @n_a1_03
    .addr @n_a1_04
    .addr @n_a1_05
    .addr @n_a2_01
    .addr @n_a2_02
    .addr @n_a2_03
    .addr @n_a2_04
    .addr @n_a2_05
    .addr @n_a3_01
    .addr @n_a3_02
    .addr @n_a3_03
    .addr @n_a3_04
    .addr @n_a3_05
    .addr @n_a4_01
    .addr @n_a4_02
    .addr @n_a4_03
    .addr @n_a4_04
    .addr @n_a4_05
    .addr @n_a5_01
    .addr @n_a5_02
    .addr @n_a5_03
    .addr @n_a5_04
    .addr @n_a5_05
    .addr @n_a5_06
    .addr @n_a6_01
    .addr @n_a6_02
    .addr @n_a6_03
    .addr @n_a6_04
    .addr @n_a6_05
    .addr @n_a6_06
    .addr @n_a6_07
    .addr @n_a6_08
    .addr @n_a7_01
    .addr @n_a7_02
    .addr @n_a7_03
    .addr @n_a7_04
    .addr @n_a8_01
    .addr @n_a8_02
    .addr @n_a8_03
    .addr @n_a9_01
    .addr @n_a9_02
    .addr @n_c1_01
    .addr @n_c1_02
    .addr @n_c1_03
    .addr @n_c1_04
    .addr @n_c1_05
    .addr @n_c2_01
    .addr @n_c2_02
    .addr @n_c2_03
    .addr @n_c2_04
    .addr @n_c2_05
    .addr @n_c2_06
    .addr @n_c3_01
    .addr @n_c3_02
    .addr @n_c3_03
    .addr @n_c3_04
    .addr @n_c3_05
    .addr @n_c13_01
    .addr @n_c13_02
    .addr @n_c13_03
    .addr @n_c14_01
    .addr @n_c14_02
    .addr @n_c11_06
    .addr @n_c11_06b
    .addr @n_c7_01
    .addr @n_c7_02
    .addr @n_c7_08
    .addr @n_c2_11
    .addr @n_c2_10
    .addr @n_c1_06
    .addr @n_c9_04
@n_a1_01:
    .byte 16
    .byte "XCE clears XH/YH"
@n_a1_02:
    .byte 21
    .byte "SEP #$10 clears XH/YH"
@n_a1_03:
    .byte 17
    .byte "E=1 forces SH=$01"
@n_a1_04:
    .byte 19
    .byte "TXS in emu -> $01FF"
@n_a1_05:
    .byte 19
    .byte "TCS in emu -> $0134"
@n_a2_01:
    .byte 22
    .byte "d,X never crosses bank"
@n_a2_02:
    .byte 21
    .byte "E=1 DL=$00 page wraps"
@n_a2_03:
    .byte 19
    .byte "E=1 DL!=$00 carries"
@n_a2_04:
    .byte 21
    .byte "Native always carries"
@n_a2_05:
    .byte 21
    .byte "[dp] never page-wraps"
@n_a3_01:
    .byte 19
    .byte "E=1 stack wraps pg1"
@n_a3_02:
    .byte 18
    .byte "PEA escapes page 1"
@n_a3_03:
    .byte 20
    .byte "PLD escapes, PLY not"
@n_a3_04:
    .byte 18
    .byte "d,S escapes page 1"
@n_a3_05:
    .byte 17
    .byte "Stack in bank $00"
@n_a4_01:
    .byte 19
    .byte "JMP (a) no page bug"
@n_a4_02:
    .byte 20
    .byte "JMP (a) ptr bank $00"
@n_a4_03:
    .byte 18
    .byte "abs,X carries bank"
@n_a4_04:
    .byte 23
    .byte "16-bit abs carries bank"
@n_a4_05:
    .byte 19
    .byte "long,X carries bank"
@n_a5_01:
    .byte 17
    .byte "+1 w when DL != 0"
@n_a5_02:
    .byte 21
    .byte "+1 p on indexed reads"
@n_a5_03:
    .byte 22
    .byte "Stores always pay +1 p"
@n_a5_04:
    .byte 23
    .byte "Decimal costs no cycles"
@n_a5_05:
    .byte 16
    .byte "16-bit RMW is +2"
@n_a5_06:
    .byte 21
    .byte "Taken branch costs +1"
@n_a6_01:
    .byte 20
    .byte "BRK vectors natively"
@n_a6_02:
    .byte 22
    .byte "COP has its own vector"
@n_a6_03:
    .byte 22
    .byte "D cleared on interrupt"
@n_a6_04:
    .byte 18
    .byte "I set on interrupt"
@n_a6_05:
    .byte 21
    .byte "Native pushes 4 bytes"
@n_a6_06:
    .byte 24
    .byte "Emulation pushes 3 bytes"
@n_a6_07:
    .byte 24
    .byte "BRK skips signature byte"
@n_a6_08:
    .byte 19
    .byte "WDM is a 2-byte NOP"
@n_a7_01:
    .byte 13
    .byte "8-bit BCD ADC"
@n_a7_02:
    .byte 14
    .byte "16-bit BCD ADC"
@n_a7_03:
    .byte 13
    .byte "8-bit BCD SBC"
@n_a7_04:
    .byte 18
    .byte "Decimal V (golden)"
@n_a8_01:
    .byte 16
    .byte "MVN fwd, A=$FFFF"
@n_a8_02:
    .byte 17
    .byte "MVN sets DBR=dest"
@n_a8_03:
    .byte 19
    .byte "MVP copies backward"
@n_a9_01:
    .byte 14
    .byte "BIT imm vs abs"
@n_a9_02:
    .byte 18
    .byte "XBA swaps A halves"
@n_c1_01:
    .byte 19
    .byte "OAM word write/read"
@n_c1_02:
    .byte 21
    .byte "OAM odd write latched"
@n_c1_03:
    .byte 21
    .byte "OAMADDR reload clears"
@n_c1_04:
    .byte 21
    .byte "OAM rd/wr one counter"
@n_c1_05:
    .byte 21
    .byte "OAM high table mirror"
@n_c2_01:
    .byte 17
    .byte "VMAIN step 1 word"
@n_c2_02:
    .byte 22
    .byte "VMAIN low-byte trigger"
@n_c2_03:
    .byte 18
    .byte "VRAM read prefetch"
@n_c2_04:
    .byte 23
    .byte "VRAM bit 15 unconnected"
@n_c2_05:
    .byte 19
    .byte "VMAIN step 32 words"
@n_c2_06:
    .byte 20
    .byte "VMAIN remap hits bus"
@n_c3_01:
    .byte 22
    .byte "CGRAM two-write commit"
@n_c3_02:
    .byte 21
    .byte "CGADD resets flipflop"
@n_c3_03:
    .byte 21
    .byte "OPHCT is a 9-bit pair"
@n_c3_04:
    .byte 18
    .byte "H counter advances"
@n_c3_05:
    .byte 21
    .byte "$213F resets flipflop"
@n_c13_01:
    .byte 22
    .byte "PPU1 open bus in $213E"
@n_c13_02:
    .byte 22
    .byte "PPU2 open bus in $213F"
@n_c13_03:
    .byte 22
    .byte "PPU1/PPU2 bus separate"
@n_c14_01:
    .byte 21
    .byte "PPU1 version (golden)"
@n_c14_02:
    .byte 21
    .byte "PPU2 version (golden)"
@n_c11_06:
    .byte 18
    .byte "MPY is 16x8 signed"
@n_c11_06b:
    .byte 17
    .byte "MPY sign handling"
@n_c7_01:
    .byte 24
    .byte "Range Over at 32 sprites"
@n_c7_02:
    .byte 20
    .byte "Time Over is slivers"
@n_c7_08:
    .byte 18
    .byte "Flags ignore $212C"
@n_c2_11:
    .byte 21
    .byte "VRAM locked in render"
@n_c2_10:
    .byte 24
    .byte "Dropped write still incs"
@n_c1_06:
    .byte 16
    .byte "OAM addr reloads"
@n_c9_04:
    .byte 21
    .byte "Overscan moves vblank"
