; GENERATED by accuracysnes-gen — do not edit by hand.
; Source of truth: tests/roms/AccuracySNES/gen/src/tests/
.p816
CATALOG_IMPL = 1
.include "runtime.inc"

.segment "TESTS"

.segment "TESTSE"

.segment "TESTSC"

.segment "TESTSD"

.segment "TESTSG"

; G1.16 — ExHiROM A23->A22
; provenance: Documented (SNESdev Wiki, memory map (ExHiROM: $80-$FF select the first 4 MiB, $00-$7D the extra 4 MiB, ROM bit 22 = inverse of A23); fullsnes)
.proc test_g1_16
    .a16
    .i16
    sep #$20
    .a8
    ; The header must read as ExHiROM.
    lda f:$00FFD5
    cmp #$25
    beq :+
    jmp @fail1
  :
    ; ExHiROM's A23->A22 rule: $C0:0000 (A23=1) selects the first 4 MiB, $40:0000 (A23=0) the
    ; extra 4 MiB. The two halves plant different landmark bytes at ROM $000000 and $400000.
    lda f:$C00000
    cmp #$A1
    beq :+
    jmp @fail2
  :
    lda f:$400000
    cmp #$E2
    beq :+
    jmp @fail3
  :
    sep #$20
    .a8
    lda #$01
    sta f:$7EE010
    jml test_restore
@fail1:
    ; the map-mode byte at $FFD5 is not $25 (ExHiROM, SlowROM), so the emulator did not select the ExHiROM board for this image
    sep #$20
    .a8
    lda #$02
    sta f:$7EE010
    jml test_restore
@fail2:
    ; $C0:0000 did not read the first-half landmark $A1 — the ExHiROM first-half ($80-$FF, A23=1) selection is wrong
    sep #$20
    .a8
    lda #$04
    sta f:$7EE010
    jml test_restore
@fail3:
    ; $40:0000 did not read the extra-half landmark $E2 — the ExHiROM extra-half ($00-$7D, A23=0) selection is wrong: A23 is not inverted into ROM offset bit 22, so both banks read one half
    sep #$20
    .a8
    lda #$06
    sta f:$7EE010
    jml test_restore
.endproc

.segment "TESTSG"

.segment "CATALOG"
.export _test_count
.export _test_entries
.export _test_names
.export _test_flags

_test_count:
    .word 1

; Entry points, 24-bit: test bodies no longer all live in bank $00.
_test_entries:
    .faraddr test_g1_16

; Per-test flags: bit0 = scores toward the pass rate, bit1 = golden-vector.
_test_flags:
    .byte $01   ; G1.16

; Menu labels, each a length-prefixed ASCII string.
_test_names:
    .addr @n_g1_16
@n_g1_16:
    .byte 16
    .byte "ExHiROM A23->A22"

; --- menu pages (AccuracyCoin-style grouping, see pages.rs) ---
.export _page_count
.export _page_names
.export _page_len
.export _page_off
.export _page_tests

_page_count:
    .word 1

_page_names:
    .addr @pn_0
@pn_0:
    .byte 14
    .byte "POWER-ON STATE"

_page_len:
    .byte 1

_page_off:
    .word 0

_page_tests:
    .word 0
